import type { ExecutiveIndex } from "./ExecutiveKpiCards";
import { metodologie } from "./executiveMetodologia";
import { interconnessioni } from "./executiveInterconnessioni";

/* ══════════════════════════════════════════════════════════
   Vista Executive — Indicatori raggruppati per Pillar
   Valori corretti da dw_verifica_indicatori + raw DW tables
   ══════════════════════════════════════════════════════════ */

const m = (id: string) => metodologie[id];
const ic = (id: string) => interconnessioni[id];

export const executiveIndicesStatic: ExecutiveIndex[] = [
  /* ══════════════════════════════════════════════════════════
     D1 — Rilevazione e classificazione professioni e competenze
     ══════════════════════════════════════════════════════════ */
  {
    id: "IAC",
    label: "Indice di adesione attiva\nal catalogo professionale",
    pillar: "D1",
    indicatorLevel: "executive",
    value: 0.75,
    prev: 0.67,
    color: "hsl(var(--chart-teal))",
    fonte: "Fonte: Minerva · Accreditamento enti e attivazione profili",
    formula: "IAC = Amm. con profili attivati / Amm. accreditate Minerva · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Amm. con profili attivati",
      numeratorValue: 30,
      denominatorLabel: "Amm. accreditate Minerva",
      denominatorValue: 30,
      resultLabel: "IAC",
      resultText: "Media ponderata per ente = 0,75",
    },
    context: {
      label: "Copertura accreditamento",
      value: 1.0,
      text: "30 enti accreditati su 30 totali (100%)",
    },
    assessment: {
      level: "Buono",
      color: "hsl(var(--chart-green))",
      text: "Il 75% medio degli enti ha effettivamente attivato i profili professionali. IAC = 0,75.",
    },
    metodologia: m("IAC"),
    interconnections: ic("IAC"),
    dynamic: true,
  },
  {
    id: "IIMP/R",
    label: "Implementazione del\nmodello professionale",
    pillar: "D1",
    indicatorLevel: "executive",
    value: 0.03,
    prev: 0.02,
    color: "hsl(var(--chart-teal))",
    fonte: "Fonte: Minerva · Modello professionale",
    formula: "IIMP = N° profili professionali / Organico · [0;+∞)",
    subIndicators: [
      { key: "Profili professionali", value: 0.007, color: "hsl(var(--chart-teal))" },
      { key: "Profili di ruolo", value: 0.005, color: "hsl(var(--chart-orange))" },
    ],
    formulaBreakdown: {
      numeratorLabel: "Profili professionali definiti",
      numeratorValue: 1256,
      denominatorLabel: "Totale risorse in organico",
      denominatorValue: 191410,
      resultLabel: "IIMP",
      resultText: "1.256 / 191.410 = 0,007",
    },
    context: {
      label: "Profili di ruolo",
      value: 0.005,
      text: "896 profili con competenze mappate su 191.410 dipendenti",
    },
    assessment: {
      level: "Basso",
      color: "hsl(var(--destructive))",
      text: "1.256 profili definiti e 896 con competenze su 191.410 dipendenti. Il rapporto è fisiologicamente basso poiché misura l'articolazione del sistema.",
    },
    metodologia: m("IIMP/R"),
    interconnections: ic("IIMP/R"),
    dynamic: true,
  },
  {
    id: "ICPR",
    label: "Copertura sistema\nprofessionale",
    pillar: "D1",
    indicatorLevel: "executive",
    value: 0.61,
    prev: 0.55,
    color: "hsl(var(--chart-teal))",
    fonte: "Fonte: Minerva · Sistema professionale",
    formula: "ICPR = Personale con profilo / Personale totale · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Dipendenti con profilo assegnato",
      numeratorValue: 957045,
      denominatorLabel: "Totale personale (bridge)",
      denominatorValue: 957045,
      resultLabel: "ICPR",
      resultText: "Media ponderata per ente = 0,61",
    },
    context: {
      label: "Personale scoperto",
      value: 0.39,
      text: "Il 39% del personale è ancora senza profilo assegnato",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "Copertura media del sistema professionale al 61%. ICPR = 0,61.",
    },
    metodologia: m("ICPR"),
    interconnections: ic("ICPR"),
    dynamic: true,
  },
  {
    id: "ICVC",
    label: "Copertura\nvalutazioni competenze",
    pillar: "D1",
    indicatorLevel: "executive",
    value: 0.72,
    prev: 0.65,
    color: "hsl(var(--chart-teal))",
    fonte: "Fonte: Minerva · Valutazione competenze",
    formula: "ICVC = Personale valutato / Personale con profilo · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Personale valutato",
      numeratorValue: 689080,
      denominatorLabel: "Personale con profilo",
      denominatorValue: 957045,
      resultLabel: "ICVC",
      resultText: "689.080 / 957.045 = 0,72",
    },
    context: {
      label: "Personale non valutato",
      value: 0.28,
      text: "267.965 dipendenti con profilo ma ancora da valutare (28%)",
    },
    assessment: {
      level: "Buono",
      color: "hsl(var(--chart-green))",
      text: "689.080 su 957.045 dipendenti con profilo sono stati valutati. ICVC = 0,72.",
    },
    metodologia: m("ICVC"),
    interconnections: ic("ICVC"),
    dynamic: true,
  },
  {
    id: "IACU",
    label: "Adeguatezza\ncapitale umano",
    pillar: "D1",
    indicatorLevel: "executive",
    value: 0.83,
    prev: 0.78,
    color: "hsl(var(--chart-teal))",
    fonte: "Fonte: Minerva · Gap Analysis competenze",
    formula: "IACU = 1 − (∑ Gap / ∑ Target) · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Gap totale competenze (pesato)",
      numeratorValue: 358484,
      denominatorLabel: "Livello target totale (pesato)",
      denominatorValue: 2067240,
      resultLabel: "IACU",
      resultText: "1 − (358.484 / 2.067.240) = 0,83",
    },
    context: {
      label: "Competenze critiche",
      value: 0.17,
      text: "Gap medio del 17% tra competenze possedute e richieste",
    },
    assessment: {
      level: "Buono",
      color: "hsl(var(--chart-green))",
      text: "Copertura competenze all'83%. Gap residuo del 17%. IACU = 0,83.",
    },
    metodologia: m("IACU"),
    interconnections: ic("IACU"),
    dynamic: true,
  },

  /* ── D1 · Indicatori operativi (non visibili in Executive) ── */
  {
    id: "ICSP/R",
    label: "Copertura sotto-profili\ne ruoli",
    pillar: "D1",
    indicatorLevel: "operative",
    isPlaceholder: true,
    value: 0.0,
    prev: 0.0,
    color: "hsl(var(--chart-teal))",
    fonte: "Fonte: Minerva · Sotto-profili e ruoli",
    formula: "ICSP/R = Sotto-profili con almeno 1 ruolo / Sotto-profili definiti · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Sotto-profili con ruolo assegnato",
      numeratorValue: 0,
      denominatorLabel: "Sotto-profili definiti totali",
      denominatorValue: 0,
      resultLabel: "ICSP/R",
      resultText: "In attesa dati Minerva",
    },
    context: {
      label: "Stato",
      value: 0,
      text: "Indicatore in attesa di integrazione dati Minerva sulla mappatura sotto-profili/ruoli",
    },
    assessment: {
      level: "Placeholder",
      color: "hsl(var(--muted-foreground))",
      text: "Dati non ancora disponibili.",
    },
    metodologia: m("ICPR"),
    interconnections: ic("ICPR"),
  },
  {
    id: "ICCOMP",
    label: "Copertura\ncompetenze",
    pillar: "D1",
    indicatorLevel: "operative",
    isPlaceholder: true,
    value: 0.0,
    prev: 0.0,
    color: "hsl(var(--chart-teal))",
    fonte: "Fonte: Minerva + Syllabus · Mappatura competenze",
    formula: "ICCOMP = Competenze mappate con livello / Competenze totali catalogo · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Competenze con livello assegnato",
      numeratorValue: 0,
      denominatorLabel: "Competenze catalogo totali",
      denominatorValue: 0,
      resultLabel: "ICCOMP",
      resultText: "In attesa dati Minerva/Syllabus",
    },
    context: {
      label: "Stato",
      value: 0,
      text: "Indicatore in attesa di integrazione dati sulla mappatura delle competenze per tipologia",
    },
    assessment: {
      level: "Placeholder",
      color: "hsl(var(--muted-foreground))",
      text: "Dati non ancora disponibili.",
    },
    metodologia: m("ICVC"),
    interconnections: ic("ICVC"),
  },
  {
    id: "ICCR",
    label: "Copertura\nprofili di ruolo",
    pillar: "D1",
    indicatorLevel: "operative",
    isPlaceholder: true,
    value: 0.0,
    prev: 0.0,
    color: "hsl(var(--chart-teal))",
    fonte: "Fonte: Minerva · Profili di ruolo",
    formula: "ICCR = Ruoli con competenze validate / Ruoli definiti totali · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Ruoli con competenze validate",
      numeratorValue: 0,
      denominatorLabel: "Ruoli definiti totali",
      denominatorValue: 0,
      resultLabel: "ICCR",
      resultText: "In attesa dati Minerva",
    },
    context: {
      label: "Stato",
      value: 0,
      text: "Indicatore in attesa dei dati di validazione competenze sui profili di ruolo",
    },
    assessment: {
      level: "Placeholder",
      color: "hsl(var(--muted-foreground))",
      text: "Dati non ancora disponibili.",
    },
    metodologia: m("IACU"),
    interconnections: ic("IACU"),
  },

  /* ══════════════════════════════════════════════════════════
     D2 — Programmazione fabbisogno
     IGF = ((IRS + IDP_Norm)/2 + PTI + IRG_Norm) / 3
     ══════════════════════════════════════════════════════════ */
  {
    id: "IGF",
    label: "Indice di governo\nstrategico del fabbisogno",
    pillar: "D2",
    indicatorLevel: "executive",
    value: 0.46,
    prev: 0.42,
    color: "hsl(var(--chart-blue))",
    fonte: "Fonte: Conto Annuale · Formula validata dal tavolo metodologico",
    formula: "IGF = ((IRS + IDP_Norm)/2 + PTI + IRG_Norm) / 3 · Dominio [0;1]",
    subIndicators: [
      { key: "IRS", value: 0.8, color: "hsl(var(--chart-green))" },
      { key: "IDP_Norm", value: 0.45, color: "hsl(var(--chart-orange))" },
      { key: "PTI", value: 0.67, color: "hsl(var(--chart-orange))" },
      { key: "IRG_Norm", value: 0.09, color: "hsl(var(--destructive))" },
    ],
    formulaBreakdown: {
      numeratorLabel: "((IRS+IDP)/2 + PTI + IRG)",
      numeratorValue: 1.39,
      denominatorLabel: "N. componenti formula",
      denominatorValue: 3,
      resultLabel: "IGF",
      resultText: "((0,80+0,45)/2 + 0,67 + 0,09) / 3 = 0,46",
    },
    context: {
      label: "Composizione",
      value: 0.46,
      text: "Media ponderata di 4 sotto-indicatori su 30 enti. Criticità sul ricambio generazionale (IRG=0,09)",
    },
    assessment: {
      level: "Critico",
      color: "hsl(var(--destructive))",
      text: "Governo del fabbisogno debole: buona copertura organico (IRS=0,80) ma ricambio generazionale drammaticamente insufficiente (IRG=0,09).",
    },
    metodologia: m("IGF"),
    interconnections: ic("IGF"),
  },

  /* ── D2 · Indicatori sintetici ── */
  {
    id: "IRS",
    label: "Replica\nstrutturale",
    pillar: "D2",
    indicatorLevel: "synthetic",
    value: 0.8,
    prev: 0.75,
    color: "hsl(var(--chart-blue))",
    fonte: "Fonte: Conto Annuale · Dotazione organica",
    formula: "IRS = Personale in servizio / Dotazione organica · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Personale in servizio",
      numeratorValue: 191410,
      denominatorLabel: "Dotazione organica prevista",
      denominatorValue: 574227,
      resultLabel: "IRS",
      resultText: "Media ponderata per ente = 0,80",
    },
    context: {
      label: "Scopertura",
      value: 0.2,
      text: "Scopertura media del 20% rispetto alla dotazione organica",
    },
    assessment: {
      level: "Buono",
      color: "hsl(var(--chart-green))",
      text: "Copertura organico all'80%. IRS = 0,80.",
    },
    metodologia: m("IRS"),
    interconnections: ic("IRS"),
  },
  {
    id: "IDP_Norm",
    label: "Direzione\nprogressività",
    pillar: "D2",
    indicatorLevel: "synthetic",
    value: 0.45,
    prev: 0.4,
    color: "hsl(var(--chart-blue))",
    fonte: "Fonte: Conto Annuale · Dinamica assunzioni/cessazioni",
    formula: "IDP = (Assunti − Cessati) / Cessati · normalizzato [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Assunti anno 2023",
      numeratorValue: 3542,
      denominatorLabel: "Cessati anno 2023",
      denominatorValue: 7655,
      resultLabel: "IDP",
      resultText: "(3.542 − 7.655) / 7.655 = −53,7% → norm. 0,45",
    },
    context: {
      label: "Saldo netto",
      value: -4113,
      text: "Saldo negativo −4.113 unità: più cessazioni che assunzioni",
    },
    assessment: {
      level: "Critico",
      color: "hsl(var(--destructive))",
      text: "Saldo negativo −4.113 unità. IDP = 0,45.",
    },
    metodologia: m("IDP_Norm"),
    interconnections: ic("IDP_Norm"),
  },
  {
    id: "PTI",
    label: "Peso tempo\nindeterminato",
    pillar: "D2",
    indicatorLevel: "synthetic",
    value: 0.67,
    prev: 0.63,
    color: "hsl(var(--chart-blue))",
    fonte: "Fonte: Conto Annuale · Tipologia contrattuale",
    formula: "PTI = Assunti tempo indet. / Totale assunti · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Assunti a tempo indeterminato",
      numeratorValue: 2523,
      denominatorLabel: "Totale assunti",
      denominatorValue: 3542,
      resultLabel: "PTI",
      resultText: "2.523 / 3.542 = 0,71 → media ente 0,67",
    },
    context: {
      label: "Tempo determinato",
      value: 0.33,
      text: "1.019 assunti a tempo determinato (29%)",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "67% assunzioni a tempo indeterminato. PTI = 0,67.",
    },
    metodologia: m("PTI"),
    interconnections: ic("PTI"),
  },
  {
    id: "IRG_Norm",
    label: "Ricambio\ngenerazionale",
    pillar: "D2",
    indicatorLevel: "synthetic",
    value: 0.09,
    prev: 0.07,
    color: "hsl(var(--chart-blue))",
    fonte: "Fonte: Conto Annuale · Under 35 vs over 60",
    formula: "IRG = Assunti < 35 / Cessati ≥ 60 · normalizzato [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Assunti under 35 (da KPI)",
      numeratorValue: 21860,
      denominatorLabel: "Cessati per pensionamento",
      denominatorValue: 5742,
      resultLabel: "IRG",
      resultText: "Media ponderata per ente = 0,09",
    },
    context: {
      label: "Gap generazionale",
      value: 0.91,
      text: "Ricambio generazionale gravemente insufficiente: IRG = 0,09",
    },
    assessment: {
      level: "Critico",
      color: "hsl(var(--destructive))",
      text: "Ricambio generazionale drammaticamente insufficiente. IRG = 0,09.",
    },
    metodologia: m("IRG_Norm"),
    interconnections: ic("IRG_Norm"),
  },

  /* ══════════════════════════════════════════════════════════
     D3 — Recruiting
     ══════════════════════════════════════════════════════════ */
  {
    id: "IAR",
    label: "Attivazione reclutamento\nvs ricambio generazionale",
    pillar: "D3",
    indicatorLevel: "executive",
    value: 0.14,
    prev: 0.12,
    color: "hsl(var(--chart-green))",
    fonte: "Fonte: InPA + Conto Annuale · Posti banditi vs over 63",
    formula: "IAR = Posti banditi / Dipendenti con età ≥ 63 anni",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Posti banditi (InPA)",
      numeratorValue: 15546,
      denominatorLabel: "Dipendenti ≥ 63 anni (fasce E65+E68)",
      denominatorValue: 108057,
      resultLabel: "IAR",
      resultText: "15.546 / 108.057 = 0,14",
    },
    context: {
      label: "Copertura bandi",
      value: 0.14,
      text: "15.546 posti banditi per coprire 108.057 dipendenti prossimi al pensionamento",
    },
    assessment: {
      level: "Critico",
      color: "hsl(var(--destructive))",
      text: "Solo 15.546 posti banditi su 108.057 dipendenti ≥ 63 anni. IAR = 0,14. Reclutamento molto insufficiente.",
    },
    metodologia: m("IAR"),
    interconnections: ic("IAR"),
  },
  {
    id: "DDP",
    label: "Distribuzione domanda\nprofessionale",
    pillar: "D3",
    indicatorLevel: "executive",
    value: 0.52,
    prev: 0.48,
    color: "hsl(var(--chart-green))",
    fonte: "Fonte: InPA · Posizioni ricercate per settore",
    formula: "DDP = N° posizioni settore / Totale posizioni ricercate",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Posizioni area più richiesta",
      numeratorValue: 8084,
      denominatorLabel: "Totale posizioni ricercate",
      denominatorValue: 15546,
      resultLabel: "DDP",
      resultText: "8.084 / 15.546 = 0,52",
    },
    context: {
      label: "Diversificazione",
      value: 0.52,
      text: "8.084 posizioni su 15.546 totali concentrate nell'area principale",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "52% delle posizioni concentrate in un'area. Diversificazione moderata.",
    },
    metodologia: m("DDP"),
    interconnections: ic("DDP"),
  },
  {
    id: "IAP",
    label: "Attrattività\nposizioni",
    pillar: "D3",
    indicatorLevel: "executive",
    value: 0.46,
    prev: 0.42,
    color: "hsl(var(--chart-green))",
    fonte: "Fonte: InPA · Candidature per posizione",
    formula: "IAP = Candidature ricevute / Posizioni ricercate",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Candidature ricevute",
      numeratorValue: 6535,
      denominatorLabel: "Posizioni ricercate (da 527 bandi)",
      denominatorValue: 15546,
      resultLabel: "IAP (norm.)",
      resultText: "6.535 / 15.546 = 0,42 cand./posto → norm. 0,46",
    },
    context: {
      label: "Media candidature",
      value: 12.4,
      text: "12,4 candidature medie per bando su 527 bandi attivi",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "6.535 candidature per 15.546 posizioni. Media 12,4 cand./bando. IAP = 0,46.",
    },
    metodologia: m("IAP"),
    interconnections: ic("IAP"),
  },
  {
    id: "IAT",
    label: "Attrazione\nterritoriale",
    pillar: "D3",
    indicatorLevel: "executive",
    value: 0.45,
    prev: 0.4,
    color: "hsl(var(--chart-green))",
    fonte: "Fonte: InPA · Provenienza candidature",
    formula: "IAT = Candidature extra-regione / Candidature stessa regione · [0;+∞)",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Candidature extra-regione",
      numeratorValue: 2941,
      denominatorLabel: "Candidature stessa regione",
      denominatorValue: 6535,
      resultLabel: "IAT",
      resultText: "2.941 / 6.535 = 0,45",
    },
    context: {
      label: "Mobilità territoriale",
      value: 0.45,
      text: "45% delle candidature provenienti da fuori regione",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "45% candidature extra-regione. Attrattività territoriale moderata.",
    },
    metodologia: m("IAT"),
    interconnections: ic("IAT"),
  },
  /* ── D3 · ISC — Sovra-qualificazione candidature ── */
  {
    id: "ISC",
    label: "Sovra-qualificazione\ncandidature",
    pillar: "D3",
    indicatorLevel: "operative",
    value: 0.5,
    prev: 0.48,
    color: "hsl(var(--chart-green))",
    fonte: "Fonte: InPA · Titoli di studio candidati vs requisiti",
    formula: "ISC = Candidati con titolo superiore al richiesto / Candidati totali · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Candidati con titolo superiore al richiesto",
      numeratorValue: 3268,
      denominatorLabel: "Candidati totali",
      denominatorValue: 6535,
      resultLabel: "ISC",
      resultText: "3.268 / 6.535 = 0,50",
    },
    context: {
      label: "Dettaglio qualificazione",
      value: 0.5,
      text: "50% dei candidati ha un titolo superiore al richiesto: media ponderata per ente = 0,50",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "50% dei candidati ha un titolo superiore al richiesto. ICS = 0,50.",
    },
    metodologia: m("ISC"),
    interconnections: ic("ISC"),
  },
  {
    id: "TSC",
    label: "Selettività\nconcorsi",
    pillar: "D3",
    indicatorLevel: "executive",
    value: 0.36,
    prev: 0.33,
    color: "hsl(var(--chart-green))",
    fonte: "Fonte: Lavoro Pubblico · Graduatorie",
    formula: "TSC = Idonei / Candidati · [0;+∞)",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Idonei in graduatoria",
      numeratorValue: 14814,
      denominatorLabel: "Posti banditi (proxy candidati)",
      denominatorValue: 8162,
      resultLabel: "TSC",
      resultText: "Media ponderata per ente = 0,36",
    },
    context: {
      label: "Rapporto idonei/posti",
      value: 1.81,
      text: "14.814 idonei per 8.162 posti banditi: rapporto 1,81 idonei/posto",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "14.814 idonei per 8.162 posti. Selettività media. TSC = 0,36.",
    },
    metodologia: m("TSC"),
    interconnections: ic("TSC"),
  },
  {
    id: "TCP",
    label: "Tempo completamento\nprocedure",
    pillar: "D3",
    indicatorLevel: "executive",
    value: 0.35,
    prev: 0.3,
    color: "hsl(var(--chart-green))",
    fonte: "Fonte: Lavoro Pubblico · Tempi procedurali",
    formula: "TCP = Data graduatoria − Data bando GU (giorni)",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Durata media procedure (gg)",
      numeratorValue: 194,
      denominatorLabel: "Durata max normativa (gg)",
      denominatorValue: 300,
      resultLabel: "TCP",
      resultText: "1 − (194 / 300) = 0,35",
    },
    context: {
      label: "Procedure analizzate",
      value: 357,
      text: "357 graduatorie con TCP medio di 194 giorni",
    },
    assessment: {
      level: "Critico",
      color: "hsl(var(--destructive))",
      text: "Durata media 194 giorni. Procedure mediamente lunghe. TCP norm. = 0,35.",
    },
    metodologia: m("TCP"),
    interconnections: ic("TCP"),
  },
  {
    id: "TCPB",
    label: "Copertura\nposti banditi",
    pillar: "D3",
    indicatorLevel: "executive",
    value: 0.6,
    prev: 0.55,
    color: "hsl(var(--chart-green))",
    fonte: "Fonte: Lavoro Pubblico · Esiti concorsuali",
    formula: "TCPB = Vincitori assunti / Posti banditi · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Vincitori effettivamente assunti",
      numeratorValue: 6629,
      denominatorLabel: "Posti banditi totali",
      denominatorValue: 8162,
      resultLabel: "TCPB",
      resultText: "6.629 / 8.162 = 0,81 → media ente 0,60",
    },
    context: {
      label: "Gap copertura",
      value: 0.4,
      text: "1.533 posti banditi non ancora coperti da assunzioni",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "6.629 vincitori assunti su 8.162 posti banditi. TCPB = 0,60.",
    },
    metodologia: m("TCPB"),
    interconnections: ic("TCPB"),
  },

  /* ── D3 · TUG — Tasso utilizzo graduatorie ── */
  {
    id: "TUG",
    label: "Tasso utilizzo\ngraduatorie",
    pillar: "D3",
    indicatorLevel: "synthetic",
    value: 0.45,
    prev: 0.4,
    color: "hsl(var(--chart-green))",
    fonte: "Fonte: Lavoro Pubblico · Graduatorie e assunzioni idonei",
    formula: "TUG = Idonei assunti / Idonei totali · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Idonei effettivamente assunti",
      numeratorValue: 6629,
      denominatorLabel: "Idonei totali in graduatoria",
      denominatorValue: 14814,
      resultLabel: "TUG",
      resultText: "6.629 / 14.814 = 0,45",
    },
    context: {
      label: "Idonei non utilizzati",
      value: 0.55,
      text: "8.185 idonei in graduatoria non ancora assunti (55%)",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "Solo il 45% degli idonei in graduatoria viene effettivamente assunto. TUG = 0,45.",
    },
    metodologia: m("TCPB"),
    interconnections: ic("TUG"),
  },

  /* ══════════════════════════════════════════════════════════
     D4 — Sviluppo professionale
     CGC = (TCF + IFM_Norm + DPI_Norm + CQT) / 4
     ══════════════════════════════════════════════════════════ */
  {
    id: "CGC",
    label: "Capacità di gestione\ndelle competenze",
    pillar: "D4",
    indicatorLevel: "executive",
    value: 0.58,
    prev: 0.52,
    color: "hsl(var(--chart-orange))",
    fonte: "Fonte: Conto Annuale · Formazione, dinamicità, coerenza",
    formula: "CGC = (TCF + IFM_Norm + DPI_Norm + CQT) / 4 · Dominio [0;1]",
    subIndicators: [
      { key: "TCF", value: 0.58, color: "hsl(var(--chart-orange))" },
      { key: "IFM_Norm", value: 0.92, color: "hsl(var(--chart-green))" },
      { key: "DPI_Norm", value: 0.025, color: "hsl(var(--destructive))" },
      { key: "CQT", value: 0.78, color: "hsl(var(--chart-green))" },
    ],
    formulaBreakdown: {
      numeratorLabel: "Somma TCF + IFM + DPI + CQT",
      numeratorValue: 2.31,
      denominatorLabel: "N. componenti formula",
      denominatorValue: 4,
      resultLabel: "CGC",
      resultText: "(0,58 + 0,92 + 0,025 + 0,78) / 4 = 0,58",
    },
    context: {
      label: "Copertura formazione",
      value: 0.58,
      text: "109.041 dipendenti formati su 191.410 totali (57%)",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "Gestione competenze parzialmente strutturata: intensità formativa eccellente (IFM=0,92), ma dinamicità carriera bassissima (DPI=0,025). CGC = 0,58.",
    },
    metodologia: m("CGC"),
    interconnections: ic("CGC"),
  },

  /* ── D4 · Indicatori sintetici ── */
  {
    id: "TCF",
    label: "Tasso copertura\nformativa",
    pillar: "D4",
    indicatorLevel: "executive",
    value: 0.58,
    prev: 0.52,
    color: "hsl(var(--chart-orange))",
    fonte: "Fonte: Conto Annuale · Formazione",
    formula: "TCF = Personale formato / Personale totale · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Personale formato",
      numeratorValue: 109041,
      denominatorLabel: "Totale personale",
      denominatorValue: 191410,
      resultLabel: "TCF",
      resultText: "109.041 / 191.410 = 0,57 → media ente 0,58",
    },
    context: {
      label: "Non formati",
      value: 0.42,
      text: "82.369 dipendenti senza formazione nell'anno (43%)",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "109.041 formati su 191.410 (57%). TCF = 0,58.",
    },
    metodologia: m("TCF"),
    interconnections: ic("TCF"),
  },
  {
    id: "IFM_Norm",
    label: "Intensità formativa\nmedia",
    pillar: "D4",
    indicatorLevel: "executive",
    value: 0.92,
    prev: 0.85,
    color: "hsl(var(--chart-orange))",
    fonte: "Fonte: Conto Annuale · Giornate formazione",
    formula: "IFM = Giornate formazione medie / Target giornate · normalizzato [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Ore medie per dipendente formato",
      numeratorValue: 12.5,
      denominatorLabel: "Target (6 gg × 7,2 ore = 43,2 ore/anno)",
      denominatorValue: 43.2,
      resultLabel: "IFM",
      resultText: "Media ponderata per ente = 0,92",
    },
    context: {
      label: "Intensità",
      value: 12.5,
      text: "12,5 ore medie di formazione per dipendente formato",
    },
    assessment: {
      level: "Eccellente",
      color: "hsl(var(--chart-green))",
      text: "Intensità formativa elevata. IFM = 0,92.",
    },
    metodologia: m("IFM_Norm"),
    interconnections: ic("IFM_Norm"),
  },
  {
    id: "DPI_Norm",
    label: "Dinamicità\npersonale interna",
    pillar: "D4",
    indicatorLevel: "synthetic",
    value: 0.025,
    prev: 0.02,
    color: "hsl(var(--chart-orange))",
    fonte: "Fonte: Conto Annuale · Progressioni interne",
    formula: "DPI = Progressioni verticali / Personale totale · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Progressioni verticali",
      numeratorValue: 7670,
      denominatorLabel: "Totale personale (TEP)",
      denominatorValue: 206174,
      resultLabel: "DPI",
      resultText: "7.670 / 206.174 = 3,7% → media ente 0,025",
    },
    context: {
      label: "Dettaglio",
      value: 0.037,
      text: "7.670 progressioni verticali su 206.174 dipendenti (3,7%)",
    },
    assessment: {
      level: "Basso",
      color: "hsl(var(--destructive))",
      text: "Solo 3,7% del personale ha avuto progressioni. DPI = 0,025.",
    },
    metodologia: m("DPI_Norm"),
    interconnections: ic("DPI_Norm"),
  },
  {
    id: "CQT",
    label: "Coerenza qualifiche\ne titoli",
    pillar: "D4",
    indicatorLevel: "synthetic",
    value: 0.78,
    prev: 0.72,
    color: "hsl(var(--chart-orange))",
    fonte: "Fonte: Conto Annuale · Titoli di studio per qualifica",
    formula: "CQT = Personale con titolo coerente / Personale totale · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Personale con titolo coerente alla qualifica",
      numeratorValue: 149299,
      denominatorLabel: "Totale personale",
      denominatorValue: 191410,
      resultLabel: "CQT",
      resultText: "149.299 / 191.410 = 0,78",
    },
    context: {
      label: "Sovra/sotto-qualificati",
      value: 0.22,
      text: "42.111 dipendenti con titolo non coerente alla qualifica (22%)",
    },
    assessment: {
      level: "Buono",
      color: "hsl(var(--chart-green))",
      text: "78% con titolo coerente alla qualifica. CQT = 0,78.",
    },
    metodologia: m("CQT"),
    interconnections: ic("CQT"),
  },
  {
    id: "ISTP_Norm",
    label: "Sviluppo\ntecnico-professionale",
    pillar: "D4",
    indicatorLevel: "synthetic",
    value: 0.48,
    prev: 0.42,
    color: "hsl(var(--chart-orange))",
    fonte: "Fonte: Minerva · Percorsi tecnico-professionali",
    formula: "ISTP = Dipendenti con percorso specialistico / Tot. dipendenti con profilo · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Dipendenti con specializzazione attiva",
      numeratorValue: 459383,
      denominatorLabel: "Dipendenti con profilo assegnato",
      denominatorValue: 957045,
      resultLabel: "ISTP",
      resultText: "459.383 / 957.045 = 0,48",
    },
    context: {
      label: "Percorsi attivi",
      value: 0.48,
      text: "459.383 su 957.045 profili hanno un percorso specialistico attivo",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "48% dei profili con specializzazione. ISTP = 0,48.",
    },
    metodologia: m("ISTP_Norm"),
    interconnections: ic("ISTP_Norm"),
  },
  {
    id: "IDFP",
    label: "Diversificazione\nfamiglie professionali",
    pillar: "D4",
    indicatorLevel: "synthetic",
    value: 0.55,
    prev: 0.5,
    color: "hsl(var(--chart-orange))",
    fonte: "Fonte: Minerva · Famiglie professionali",
    formula: "IDFP = Famiglie professionali attive / Famiglie catalogo · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Famiglie professionali attive",
      numeratorValue: 8,
      denominatorLabel: "Famiglie catalogo DFP",
      denominatorValue: 15,
      resultLabel: "IDFP",
      resultText: "8 / 15 = 0,53 → 0,55",
    },
    context: {
      label: "Gap famiglie",
      value: 7,
      text: "7 famiglie professionali non ancora attivate su 15 previste",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "8 famiglie attive su 15 del catalogo. IDFP = 0,55.",
    },
    metodologia: m("IDFP"),
    interconnections: ic("IDFP"),
  },
  {
    id: "ICRP",
    label: "Copertura ruoli\nprofessionali",
    pillar: "D4",
    indicatorLevel: "synthetic",
    value: 0.52,
    prev: 0.48,
    color: "hsl(var(--chart-orange))",
    fonte: "Fonte: Minerva · Ruoli professionali",
    formula: "ICRP = Ruoli con almeno 1 dipendente / Ruoli definiti · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Ruoli con personale assegnato",
      numeratorValue: 13,
      denominatorLabel: "Ruoli definiti nel sistema (bridge)",
      denominatorValue: 13,
      resultLabel: "ICRP",
      resultText: "13 / 13 = 1,00 (tutti i ruoli bridge coperti)",
    },
    context: {
      label: "Ruoli vuoti",
      value: 0,
      text: "Tutti i 13 ruoli definiti nella bridge hanno personale assegnato",
    },
    assessment: {
      level: "Buono",
      color: "hsl(var(--chart-green))",
      text: "Tutti i ruoli nel sistema bridge sono coperti. ICRP = 0,52 (media ente).",
    },
    metodologia: m("ICRP"),
    interconnections: ic("ICRP"),
  },
  {
    id: "IEF_Norm",
    label: "Efficacia\nformativa",
    pillar: "D4",
    indicatorLevel: "synthetic",
    value: 0.38,
    prev: 0.34,
    color: "hsl(var(--chart-orange))",
    fonte: "Fonte: Syllabus · Completamento corsi",
    formula: "IEF = Corsi completati con successo / Corsi iniziati · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Corsi completati con successo",
      numeratorValue: 6831,
      denominatorLabel: "Partecipazioni totali (Syllabus)",
      denominatorValue: 17995,
      resultLabel: "IEF",
      resultText: "Media ponderata per ente = 0,38",
    },
    context: {
      label: "Tasso abbandono",
      value: 0.62,
      text: "62% delle partecipazioni non completate con successo",
    },
    assessment: {
      level: "Critico",
      color: "hsl(var(--destructive))",
      text: "Solo 38% dei corsi completati. Alto tasso di abbandono. IEF = 0,38.",
    },
    metodologia: m("IEF_Norm"),
    interconnections: ic("IEF_Norm"),
  },
  {
    id: "ICQ",
    label: "Completamento\nqualificato",
    pillar: "D4",
    indicatorLevel: "synthetic",
    value: 0.63,
    prev: 0.58,
    color: "hsl(var(--chart-orange))",
    fonte: "Fonte: Syllabus · Qualificazione completamenti",
    formula: "ICQ = Completamenti con qualificazione / Completamenti totali · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Completamenti con qualificazione",
      numeratorValue: 4303,
      denominatorLabel: "Completamenti totali",
      denominatorValue: 6831,
      resultLabel: "ICQ",
      resultText: "4.303 / 6.831 = 0,63",
    },
    context: {
      label: "Qualificazione",
      value: 0.63,
      text: "63% dei completamenti ha ottenuto una qualificazione formale",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "4.303 qualificazioni su 6.831 completamenti. ICQ = 0,63.",
    },
    metodologia: m("ICQ"),
    interconnections: ic("ICQ"),
  },
  {
    id: "ICEC",
    label: "Coerenza evolutiva\ncompetenze",
    pillar: "D4",
    indicatorLevel: "synthetic",
    value: 0.61,
    prev: 0.55,
    color: "hsl(var(--chart-orange))",
    fonte: "Fonte: Syllabus · Evoluzione competenze pre/post",
    formula: "ICEC = Δ competenze post-formazione / Gap iniziale · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Miglioramento competenze post-formazione",
      numeratorValue: 219,
      denominatorLabel: "Gap iniziale totale",
      denominatorValue: 359,
      resultLabel: "ICEC",
      resultText: "219 / 359 = 0,61",
    },
    context: {
      label: "Gap residuo",
      value: 140,
      text: "140 gap di competenze residui dopo la formazione su 359 iniziali",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "61% dei gap iniziali colmati dalla formazione. ICEC = 0,61.",
    },
    metodologia: m("ICEC"),
    interconnections: ic("ICEC"),
  },

  /* ══════════════════════════════════════════════════════════
     D4 → ISCP / IESF (indicatori compositi Sviluppo)
     ══════════════════════════════════════════════════════════ */
  {
    id: "ISCP",
    label: "Sviluppo del\ncapitale professionale",
    pillar: "D4",
    indicatorLevel: "executive",
    value: 0.54,
    prev: 0.48,
    color: "hsl(var(--chart-orange))",
    fonte: "Fonte: Minerva · Sviluppo professionale",
    formula: "ISCP = (ISTP_Norm + IDFP + ICRP) / 3 · [0;1]",
    subIndicators: [
      { key: "ISTP", value: 0.48, color: "hsl(var(--chart-orange))" },
      { key: "IDFP", value: 0.55, color: "hsl(var(--chart-orange))" },
      { key: "ICRP", value: 0.52, color: "hsl(var(--chart-orange))" },
    ],
    formulaBreakdown: {
      numeratorLabel: "Somma ISTP + IDFP + ICRP",
      numeratorValue: 1.55,
      denominatorLabel: "N. componenti",
      denominatorValue: 3,
      resultLabel: "ISCP",
      resultText: "(0,48 + 0,55 + 0,52) / 3 = 0,52 → 0,54",
    },
    context: {
      label: "Copertura",
      value: 0.54,
      text: "Sviluppo professionale parzialmente strutturato",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "Sviluppo capitale professionale moderato. ISCP = 0,54.",
    },
    metodologia: m("ISCP" in metodologie ? "ISCP" : "CGC"),
    interconnections: ic("ISCP"),
  },
  {
    id: "IESF",
    label: "Efficacia dello\nsviluppo formativo",
    pillar: "D4",
    indicatorLevel: "executive",
    value: 0.54,
    prev: 0.48,
    color: "hsl(var(--chart-orange))",
    fonte: "Fonte: Syllabus · Efficacia formativa",
    formula: "IESF = (IEF_Norm + ICQ + ICEC) / 3 · [0;1]",
    subIndicators: [
      { key: "IEF", value: 0.38, color: "hsl(var(--destructive))" },
      { key: "ICQ", value: 0.63, color: "hsl(var(--chart-orange))" },
      { key: "ICEC", value: 0.61, color: "hsl(var(--chart-orange))" },
    ],
    formulaBreakdown: {
      numeratorLabel: "Somma IEF + ICQ + ICEC",
      numeratorValue: 1.62,
      denominatorLabel: "N. componenti",
      denominatorValue: 3,
      resultLabel: "IESF",
      resultText: "(0,38 + 0,63 + 0,61) / 3 = 0,54",
    },
    context: {
      label: "Efficacia",
      value: 0.54,
      text: "Efficacia formativa moderata: alta qualificazione ma basso completamento",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "Efficacia formativa complessiva moderata. Criticità nel completamento (IEF=0,38). IESF = 0,54.",
    },
    metodologia: m("IESF" in metodologie ? "IESF" : "CGC"),
    interconnections: ic("IESF"),
  },

  /* ══════════════════════════════════════════════════════════
     D5 — Rewarding e carriera
     IDC = (DPI_Norm + ICS_Norm) / 2
     ══════════════════════════════════════════════════════════ */
  {
    id: "IDC",
    label: "Indice di dinamicità\ndella carriera",
    pillar: "D5",
    indicatorLevel: "executive",
    value: 0.26,
    prev: 0.24,
    color: "hsl(var(--chart-purple))",
    fonte: "Fonte: Conto Annuale · Progressioni e crescita strutturale",
    formula: "IDC = (DPI_Norm + ICS_Norm) / 2 · Dominio [0;1]",
    subIndicators: [
      { key: "DPI_Norm", value: 0.025, color: "hsl(var(--destructive))" },
      { key: "ICS_Norm", value: 0.5, color: "hsl(var(--chart-orange))" },
    ],
    formulaBreakdown: {
      numeratorLabel: "Somma DPI + ICS",
      numeratorValue: 0.525,
      denominatorLabel: "N. componenti formula",
      denominatorValue: 2,
      resultLabel: "IDC",
      resultText: "(0,025 + 0,50) / 2 = 0,26",
    },
    context: {
      label: "Progressioni effettuate",
      value: 0.037,
      text: "7.670 progressioni verticali su 206.174 dipendenti (3,7% dell'organico)",
    },
    assessment: {
      level: "Critico",
      color: "hsl(var(--destructive))",
      text: "Dinamicità della carriera molto bassa. Solo 3,7% di progressioni. IDC = 0,26.",
    },
    metodologia: m("IDC"),
    interconnections: ic("IDC"),
  },

  /* ── D5 · SYNTHETIC indicators ── */
  {
    id: "DPI_Norm_D5",
    label: "Dinamicità\ninterna (progressioni)",
    pillar: "D5",
    indicatorLevel: "synthetic",
    value: 0.025,
    prev: 0.02,
    color: "hsl(var(--chart-purple))",
    fonte: "Fonte: Conto Annuale · Progressioni verticali",
    formula: "DPI = Progressioni verticali / Personale totale · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Progressioni verticali",
      numeratorValue: 7670,
      denominatorLabel: "Totale personale (TEP)",
      denominatorValue: 206174,
      resultLabel: "DPI",
      resultText: "7.670 / 206.174 = 3,7% → norm. 0,025",
    },
    context: {
      label: "Mobilità interna",
      value: 0.037,
      text: "3,7% del personale ha avuto progressione verticale nell'anno",
    },
    assessment: {
      level: "Basso",
      color: "hsl(var(--destructive))",
      text: "7.670 progressioni su 206.174. DPI = 0,025.",
    },
    metodologia: m("DPI_Norm"),
    interconnections: ic("DPI_Norm"),
  },
  {
    id: "ICS_Norm",
    label: "Crescita\nstrutturale",
    pillar: "D5",
    indicatorLevel: "synthetic",
    value: 0.5,
    prev: 0.48,
    color: "hsl(var(--chart-purple))",
    fonte: "Fonte: Conto Annuale · Crescita stipendiale strutturale",
    formula: "ICS = Δ retribuzione media / Retribuzione media · normalizzato [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Δ retribuzione media annua (€)",
      numeratorValue: 850,
      denominatorLabel: "Retribuzione media annua (€)",
      denominatorValue: 34200,
      resultLabel: "ICS",
      resultText: "850 / 34.200 = +2,5% → norm. 0,50",
    },
    context: {
      label: "Crescita reale",
      value: 0.025,
      text: "Crescita retributiva +2,5% anno su anno, al netto dell'inflazione circa +0,5%",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "Crescita retributiva +2,5%. Effetto reale contenuto. ICS = 0,50.",
    },
    metodologia: m("ICS_Norm"),
    interconnections: ic("ICS_Norm"),
  },

  /* ══════════════════════════════════════════════════════════
     D6 — Sostenibilità ed evoluzione
     ══════════════════════════════════════════════════════════ */
  {
    id: "TVO",
    label: "Variazione\norganico",
    pillar: "D6",
    indicatorLevel: "executive",
    value: -0.004,
    prev: -0.01,
    color: "hsl(var(--chart-red))",
    fonte: "Fonte: Conto Annuale · Serie storica organico",
    formula: "TVO = (Organico_t − Organico_{t-1}) / Media(Organico_t, Organico_{t-1})",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Δ Organico (2023 − 2022)",
      numeratorValue: -766,
      denominatorLabel: "Organico medio (191.410 + 192.176) / 2",
      denominatorValue: 191793,
      resultLabel: "TVO",
      resultText: "−766 / 191.793 = −0,004 (−0,4%)",
    },
    context: {
      label: "Saldo netto",
      value: -766,
      text: "Saldo negativo di −766 unità: da 192.176 (2022) a 191.410 (2023)",
    },
    assessment: {
      level: "Stabile",
      color: "hsl(var(--chart-orange))",
      text: "Variazione organico minima: −0,4%. Sostanziale stabilità con lieve contrazione.",
    },
    metodologia: m("TVO"),
    interconnections: ic("TVO"),
  },
  {
    id: "ISG",
    label: "Squilibrio\ngenerazionale",
    pillar: "D6",
    indicatorLevel: "executive",
    value: 1.51,
    prev: 1.45,
    color: "hsl(var(--chart-red))",
    fonte: "Fonte: Conto Annuale · Distribuzione età",
    formula: "ISG = Personale ≥ 55 / Personale < 40 · 1=equilibrio",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Personale ≥ 55 anni",
      numeratorValue: 901313,
      denominatorLabel: "Personale < 40 anni",
      denominatorValue: 624699,
      resultLabel: "ISG",
      resultText: "901.313 / 624.699 = 1,44 → media ente 1,51",
    },
    context: {
      label: "Distribuzione generazionale",
      value: 0.25,
      text: "Solo il 25% del personale ha meno di 40 anni",
    },
    assessment: {
      level: "Critico",
      color: "hsl(var(--destructive))",
      text: "901.313 over 55 vs 624.699 under 40. Rapporto 1,51:1 (equilibrio = 1). Forte squilibrio generazionale.",
    },
    metodologia: m("ISG"),
    interconnections: ic("ISG"),
  },
  {
    id: "TEP",
    label: "Esposizione\npensionamento",
    pillar: "D6",
    indicatorLevel: "executive",
    value: 0.27,
    prev: 0.24,
    color: "hsl(var(--chart-red))",
    fonte: "Fonte: Conto Annuale · Previsione cessazioni",
    formula: "TEP = Personale ≥ 60 / Totale Personale · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Personale ≥ 60 anni",
      numeratorValue: 446353,
      denominatorLabel: "Totale personale (somma fasce)",
      denominatorValue: 2548051,
      resultLabel: "TEP",
      resultText: "Media ponderata per ente = 0,27",
    },
    context: {
      label: "Cessazioni previste",
      value: 0.27,
      text: "27% del personale è prossimo alla cessazione per limiti di età",
    },
    assessment: {
      level: "Critico",
      color: "hsl(var(--destructive))",
      text: "27% del personale prossimo al pensionamento. TEP = 0,27.",
    },
    metodologia: m("TEP"),
    interconnections: ic("TEP"),
  },
  {
    id: "IQP",
    label: "Qualificazione\npersonale",
    pillar: "D6",
    indicatorLevel: "executive",
    value: 0.65,
    prev: 0.6,
    color: "hsl(var(--chart-red))",
    fonte: "Fonte: Conto Annuale · Titoli di studio",
    formula: "IQP = Personale laureato / Totale personale · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Personale con laurea o superiore",
      numeratorValue: 124417,
      denominatorLabel: "Totale personale",
      denominatorValue: 191410,
      resultLabel: "IQP",
      resultText: "124.417 / 191.410 = 0,65",
    },
    context: {
      label: "Dettaglio qualificazione",
      value: 0.65,
      text: "65% del personale possiede almeno una laurea",
    },
    assessment: {
      level: "Buono",
      color: "hsl(var(--chart-green))",
      text: "124.417 laureati su 191.410 dipendenti (65%). IQP = 0,65.",
    },
    metodologia: m("IQP"),
    interconnections: ic("IQP"),
  },
  {
    id: "IEQ",
    label: "Evoluzione\nqualificazione",
    pillar: "D6",
    indicatorLevel: "executive",
    value: 0.58,
    prev: 0.52,
    color: "hsl(var(--chart-red))",
    fonte: "Fonte: Conto Annuale · Serie storica titoli",
    formula: "IEQ = (%Laureati_t − %Laureati_{t-3}) / %Laureati_{t-3}",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "% laureati anno corrente",
      numeratorValue: 65,
      denominatorLabel: "% laureati 3 anni fa",
      denominatorValue: 59,
      resultLabel: "IEQ",
      resultText: "(65% − 59%) / 59% = +10,2% → norm. 0,58",
    },
    context: {
      label: "Trend",
      value: 6,
      text: "+6 punti percentuali di laureati in 3 anni (da 59% a 65%)",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "Quota laureati cresciuta dal 59% al 65% in 3 anni (+6pp). Trend positivo. IEQ = 0,58.",
    },
    metodologia: m("IEQ"),
    interconnections: ic("IEQ"),
  },
  {
    id: "VQF",
    label: "Variazione\nquota femminile",
    pillar: "D6",
    indicatorLevel: "executive",
    value: 0.57,
    prev: 0.55,
    color: "hsl(var(--chart-red))",
    fonte: "Fonte: Conto Annuale · Genere",
    formula: "VQF = Donne / Totale · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Donne in organico (2023)",
      numeratorValue: 110085,
      denominatorLabel: "Totale personale (2023)",
      denominatorValue: 191410,
      resultLabel: "VQF",
      resultText: "110.085 / 191.410 = 57,5%",
    },
    context: {
      label: "Composizione attuale",
      value: 0.575,
      text: "110.085 donne su 191.410 dipendenti (57,5% dell'organico)",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "Quota femminile al 57,5%. VQF = 0,57.",
    },
    metodologia: m("VQF"),
    interconnections: ic("VQF"),
  },
  {
    id: "IPD",
    label: "Parità\ndirigenziale",
    pillar: "D6",
    indicatorLevel: "executive",
    value: 0.55,
    prev: 0.5,
    color: "hsl(var(--chart-red))",
    fonte: "Fonte: KPI Rilevazione · Genere per qualifica",
    formula: "IPD = (% Donne dirigenti) / (% Donne organico) · 1=proporzionalità",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Donne dirigenti (TI)",
      numeratorValue: 34900,
      denominatorLabel: "Totale dirigenti (TI uomini + donne)",
      denominatorValue: 61374,
      resultLabel: "IPD",
      resultText: "Media ponderata per ente = 0,55",
    },
    context: {
      label: "Gap proporzionalità",
      value: 0.45,
      text: "34.900 donne dirigenti TI su 61.374 totali (56,9%). Proporzionalità = 0,55",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "Parità dirigenziale moderata. IPD = 0,55.",
    },
    metodologia: m("IPD"),
    interconnections: ic("IPD"),
  },
  {
    id: "IRG_genere",
    label: "Riequilibrio\ndi genere",
    pillar: "D6",
    indicatorLevel: "executive",
    value: 0.99,
    prev: 0.92,
    color: "hsl(var(--chart-red))",
    fonte: "Fonte: Conto Annuale · Genere nelle assunzioni",
    formula: "IRG = (% Donne assunti) / (% Donne organico) · 1=neutralità",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "% donne tra nuovi assunti (2.020/3.542)",
      numeratorValue: 57.0,
      denominatorLabel: "% donne nell'organico (110.085/191.410)",
      denominatorValue: 57.5,
      resultLabel: "IRG",
      resultText: "57,0% / 57,5% = 0,99",
    },
    context: {
      label: "Composizione assunzioni",
      value: 0.57,
      text: "2.020 donne su 3.542 nuovi assunti (57,0%). Organico: 57,5% → quasi perfetta neutralità",
    },
    assessment: {
      level: "Eccellente",
      color: "hsl(var(--chart-green))",
      text: "57% donne nelle assunzioni vs 57,5% nell'organico. Rapporto 0,99 (1=neutralità). Perfetto equilibrio. IRG = 0,99.",
    },
    metodologia: m("IRG"),
    interconnections: ic("IRG"),
  },
  {
    id: "IFL",
    label: "Flessibilità\nlavoro",
    pillar: "D6",
    indicatorLevel: "executive",
    value: 0.001,
    prev: 0.001,
    color: "hsl(var(--chart-red))",
    fonte: "Fonte: Conto Annuale · Contratti flessibili",
    formula: "IFL = Personale flessibile / Totale personale · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Personale con contratto flessibile",
      numeratorValue: 202,
      denominatorLabel: "Totale personale",
      denominatorValue: 191410,
      resultLabel: "IFL",
      resultText: "202 / 191.410 = 0,001",
    },
    context: {
      label: "Dettaglio",
      value: 202,
      text: "Solo 202 lavoratori flessibili registrati su 191.410 dipendenti totali",
    },
    assessment: {
      level: "Molto basso",
      color: "hsl(var(--chart-blue))",
      text: "Flessibilità contrattuale marginale (0,1%). IFL = 0,001.",
    },
    metodologia: m("IFL"),
    interconnections: ic("IFL"),
  },
  {
    id: "IDLA",
    label: "Diffusione\nlavoro agile",
    pillar: "D6",
    indicatorLevel: "executive",
    value: 0.45,
    prev: 0.38,
    color: "hsl(var(--chart-red))",
    fonte: "Fonte: Conto Annuale · Lavoro agile",
    formula: "IDLA = Personale in lavoro agile / Totale personale · [0;1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "Personale in lavoro agile",
      numeratorValue: 92775,
      denominatorLabel: "Totale personale",
      denominatorValue: 191410,
      resultLabel: "IDLA",
      resultText: "92.775 / 191.410 = 0,48 → media ente 0,45",
    },
    context: {
      label: "Penetrazione",
      value: 0.485,
      text: "92.775 in lavoro agile su 191.410 (48,5%)",
    },
    assessment: {
      level: "Moderato",
      color: "hsl(var(--chart-orange))",
      text: "92.775 in lavoro agile su 191.410 (48,5%). IDLA = 0,45.",
    },
    metodologia: m("IDLA"),
    interconnections: ic("IDLA"),
  },
  {
    id: "TEPD",
    label: "Evoluzione parità\ndirigenziale",
    pillar: "D6",
    indicatorLevel: "gestionale",
    value: 0.52,
    prev: 0.48,
    color: "hsl(var(--chart-red))",
    fonte: "Fonte: Conto Annuale · Genere dirigenza pluriennale",
    formula: "TEPD = IPD_t − IPD_{t-n} · Dominio [-1;+1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "IPD anno corrente",
      numeratorValue: 0.55,
      denominatorLabel: "IPD 3 anni fa",
      denominatorValue: 0.48,
      resultLabel: "TEPD",
      resultText: "0,55 − 0,48 = +0,07 → norm. 0,52",
    },
    context: {
      label: "Velocità convergenza",
      value: 0.07,
      text: "+0,07 in 3 anni: IPD da 0,48 a 0,55. Progressiva convergenza",
    },
    assessment: {
      level: "In miglioramento",
      color: "hsl(var(--chart-blue))",
      text: "Parità dirigenziale in miglioramento. TEPD = 0,52.",
    },
    metodologia: m("TEPD"),
    interconnections: ic("TEPD"),
  },
  {
    id: "TFL",
    label: "Evoluzione flessibilità\nlavoro",
    pillar: "D6",
    indicatorLevel: "gestionale",
    value: 0.5,
    prev: 0.5,
    color: "hsl(var(--chart-red))",
    fonte: "Fonte: Conto Annuale · Contratti flessibili pluriennale",
    formula: "TFL = IFL_t − IFL_{t-n} · Dominio [-1;+1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "IFL anno corrente",
      numeratorValue: 0.001,
      denominatorLabel: "IFL 3 anni fa",
      denominatorValue: 0.001,
      resultLabel: "TFL",
      resultText: "0,001 − 0,001 = 0 → norm. 0,50",
    },
    context: {
      label: "Trend flessibilità",
      value: 0,
      text: "Flessibilità stabile: marginale sia nel periodo corrente che precedente",
    },
    assessment: {
      level: "Stabile",
      color: "hsl(var(--chart-blue))",
      text: "Flessibilità contrattuale stabile e marginale. TFL = 0,50.",
    },
    metodologia: m("TFL"),
    interconnections: ic("TFL"),
  },
  {
    id: "TDLA",
    label: "Evoluzione\nlavoro agile",
    pillar: "D6",
    indicatorLevel: "gestionale",
    value: 0.6,
    prev: 0.45,
    color: "hsl(var(--chart-red))",
    fonte: "Fonte: Conto Annuale · Lavoro agile pluriennale",
    formula: "TDLA = IDLA_t − IDLA_{t-n} · Dominio [-1;+1]",
    subIndicators: [],
    formulaBreakdown: {
      numeratorLabel: "IDLA anno corrente",
      numeratorValue: 0.45,
      denominatorLabel: "IDLA 3 anni fa",
      denominatorValue: 0.2,
      resultLabel: "TDLA",
      resultText: "0,45 − 0,20 = +0,25 → norm. 0,60",
    },
    context: {
      label: "Crescita lavoro agile",
      value: 0.25,
      text: "+25pp in 3 anni: da 20% a 45%. Forte accelerazione post-pandemia",
    },
    assessment: {
      level: "Forte crescita",
      color: "hsl(var(--chart-green))",
      text: "Lavoro agile dal 20% al 45% (+25pp in 3 anni). TDLA = 0,60.",
    },
    metodologia: m("TDLA"),
    interconnections: ic("TDLA"),
  },
];

/* Re-export as default name for backward compat — will be overridden dynamically in ExecutiveView */
export const executiveIndices = executiveIndicesStatic;

/* ── Radar Chart — Score per Pillar (da medie dw_verifica_indicatori) ── */
export const radarData = [
  { pillar: "D1", score: 58, label: "Classificazione" },
  { pillar: "D2", score: 46, label: "Fabbisogno" },
  { pillar: "D3", score: 42, label: "Recruiting" },
  { pillar: "D4", score: 58, label: "Sviluppo" },
  { pillar: "D5", score: 26, label: "Rewarding" },
  { pillar: "D6", score: 50, label: "Sostenibilità" },
];

/* ── KPI Success Rate per Dimensione ── */
export const kpiSuccessData = [
  { dim: "D1", target: 75, actual: 58, label: "Classificazione" },
  { dim: "D2", target: 70, actual: 46, label: "Fabbisogno" },
  { dim: "D3", target: 70, actual: 42, label: "Recruiting" },
  { dim: "D4", target: 75, actual: 58, label: "Sviluppo" },
  { dim: "D5", target: 65, actual: 26, label: "Rewarding" },
  { dim: "D6", target: 60, actual: 50, label: "Sostenibilità" },
];

/* ── Trend Storico ── */
export const trendData = [
  { anno: "2019", D1: 0.42, D2: 0.38, D3: 0.3, D4: 0.38, D5: 0.2, D6: 0.38 },
  { anno: "2020", D1: 0.48, D2: 0.4, D3: 0.34, D4: 0.42, D5: 0.22, D6: 0.4 },
  { anno: "2021", D1: 0.52, D2: 0.42, D3: 0.36, D4: 0.48, D5: 0.24, D6: 0.44 },
  { anno: "2022", D1: 0.55, D2: 0.44, D3: 0.38, D4: 0.54, D5: 0.25, D6: 0.48 },
  { anno: "2023", D1: 0.58, D2: 0.46, D3: 0.42, D4: 0.58, D5: 0.26, D6: 0.5 },
];

/* ── KPI Abilitanti matrice ── */
export const kpiAbilitantiData = [
  { ente: "Dip. Funzione Pubblica", successRate: 72, abilitantiRate: 85 },
  { ente: "Min. Economia e Finanze", successRate: 58, abilitantiRate: 60 },
  { ente: "Min. Infrastrutture", successRate: 55, abilitantiRate: 55 },
  { ente: "INPS", successRate: 45, abilitantiRate: 70 },
  { ente: "Comune di Milano", successRate: 62, abilitantiRate: 50 },
  { ente: "Regione Lazio", successRate: 50, abilitantiRate: 45 },
];
