-- public.v_kpi_ente_wide : pivot per-ente (EAV -> wide) da dwh.ft_questionari_globale
-- Una riga per (id_ente, cf_ente, rilevazione, progetto); una colonna per raw_element.
-- Base per ricostruire dw_kpi_rilevazione e le tabelle dei fatti.
DROP MATERIALIZED VIEW IF EXISTS public.v_kpi_ente_wide CASCADE;
CREATE MATERIALIZED VIEW public.v_kpi_ente_wide AS
SELECT
  e.id::int            AS id_ente,
  f.cf_ente            AS cfiscale,
  f.rilevazione        AS rilevazione,
  f.progetto           AS progetto,
  MAX(CASE WHEN f.raw_element = '1.1' THEN f.valore_num END) AS "q_1_1",
  MAX(CASE WHEN f.raw_element = '1.2' THEN f.valore_num END) AS "q_1_2",
  MAX(CASE WHEN f.raw_element = '1.2.a' THEN f.valore_num END) AS "q_1_2_a",
  MAX(CASE WHEN f.raw_element = '1.2.b' THEN f.valore_num END) AS "q_1_2_b",
  MAX(CASE WHEN f.raw_element = '1.3' THEN f.valore_num END) AS "q_1_3",
  MAX(CASE WHEN f.raw_element = '1.4' THEN f.valore_num END) AS "q_1_4",
  MAX(CASE WHEN f.raw_element = '1.5' THEN f.valore_num END) AS "q_1_5",
  MAX(CASE WHEN f.raw_element = '1.6' THEN f.valore_num END) AS "q_1_6",
  MAX(CASE WHEN f.raw_element = '2.1' THEN f.valore_num END) AS "q_2_1",
  MAX(CASE WHEN f.raw_element = '2.2' THEN f.valore_num END) AS "q_2_2",
  MAX(CASE WHEN f.raw_element = '2.3' THEN f.valore_num END) AS "q_2_3",
  MAX(CASE WHEN f.raw_element = '2.4' THEN f.valore_num END) AS "q_2_4",
  MAX(CASE WHEN f.raw_element = '2.5' THEN f.valore_num END) AS "q_2_5",
  MAX(CASE WHEN f.raw_element = '2.6' THEN f.valore_num END) AS "q_2_6",
  MAX(CASE WHEN f.raw_element = '3.1' THEN f.valore_num END) AS "q_3_1",
  MAX(CASE WHEN f.raw_element = '3.2' THEN f.valore_num END) AS "q_3_2",
  MAX(CASE WHEN f.raw_element = '3.3' THEN f.valore_num END) AS "q_3_3",
  MAX(CASE WHEN f.raw_element = '3.4' THEN f.valore_num END) AS "q_3_4",
  MAX(CASE WHEN f.raw_element = '3.5' THEN f.valore_num END) AS "q_3_5",
  MAX(CASE WHEN f.raw_element = '3.6' THEN f.valore_num END) AS "q_3_6",
  MAX(CASE WHEN f.raw_element = '4.1' THEN f.valore_num END) AS "q_4_1",
  MAX(CASE WHEN f.raw_element = '4.2' THEN f.valore_num END) AS "q_4_2",
  MAX(CASE WHEN f.raw_element = '4.3' THEN f.valore_num END) AS "q_4_3",
  MAX(CASE WHEN f.raw_element = '5.1' THEN f.valore_num END) AS "q_5_1",
  MAX(CASE WHEN f.raw_element = '5.2' THEN f.valore_num END) AS "q_5_2",
  MAX(CASE WHEN f.raw_element = '5.3' THEN f.valore_num END) AS "q_5_3",
  MAX(CASE WHEN f.raw_element = '6.1' THEN f.valore_num END) AS "q_6_1",
  MAX(CASE WHEN f.raw_element = '6.10' THEN f.valore_num END) AS "q_6_10",
  MAX(CASE WHEN f.raw_element = '6.10.a' THEN f.valore_num END) AS "q_6_10_a",
  MAX(CASE WHEN f.raw_element = '6.10.b' THEN f.valore_num END) AS "q_6_10_b",
  MAX(CASE WHEN f.raw_element = '6.11' THEN f.valore_num END) AS "q_6_11",
  MAX(CASE WHEN f.raw_element = '6.11.a' THEN f.valore_num END) AS "q_6_11_a",
  MAX(CASE WHEN f.raw_element = '6.11.b' THEN f.valore_num END) AS "q_6_11_b",
  MAX(CASE WHEN f.raw_element = '6.12.a' THEN f.valore_num END) AS "q_6_12_a",
  MAX(CASE WHEN f.raw_element = '6.12.b' THEN f.valore_num END) AS "q_6_12_b",
  MAX(CASE WHEN f.raw_element = '6.13' THEN f.valore_num END) AS "q_6_13",
  MAX(CASE WHEN f.raw_element = '6.13.a' THEN f.valore_num END) AS "q_6_13_a",
  MAX(CASE WHEN f.raw_element = '6.13.b' THEN f.valore_num END) AS "q_6_13_b",
  MAX(CASE WHEN f.raw_element = '6.14.a' THEN f.valore_num END) AS "q_6_14_a",
  MAX(CASE WHEN f.raw_element = '6.14.b' THEN f.valore_num END) AS "q_6_14_b",
  MAX(CASE WHEN f.raw_element = '6.15' THEN f.valore_num END) AS "q_6_15",
  MAX(CASE WHEN f.raw_element = '6.16' THEN f.valore_num END) AS "q_6_16",
  MAX(CASE WHEN f.raw_element = '6.16.a' THEN f.valore_num END) AS "q_6_16_a",
  MAX(CASE WHEN f.raw_element = '6.16.b' THEN f.valore_num END) AS "q_6_16_b",
  MAX(CASE WHEN f.raw_element = '6.17' THEN f.valore_num END) AS "q_6_17",
  MAX(CASE WHEN f.raw_element = '6.17.a' THEN f.valore_num END) AS "q_6_17_a",
  MAX(CASE WHEN f.raw_element = '6.17.b' THEN f.valore_num END) AS "q_6_17_b",
  MAX(CASE WHEN f.raw_element = '6.17.c' THEN f.valore_num END) AS "q_6_17_c",
  MAX(CASE WHEN f.raw_element = '6.17.d' THEN f.valore_num END) AS "q_6_17_d",
  MAX(CASE WHEN f.raw_element = '6.18' THEN f.valore_num END) AS "q_6_18",
  MAX(CASE WHEN f.raw_element = '6.18.a' THEN f.valore_num END) AS "q_6_18_a",
  MAX(CASE WHEN f.raw_element = '6.18.b' THEN f.valore_num END) AS "q_6_18_b",
  MAX(CASE WHEN f.raw_element = '6.18.c' THEN f.valore_num END) AS "q_6_18_c",
  MAX(CASE WHEN f.raw_element = '6.18.d' THEN f.valore_num END) AS "q_6_18_d",
  MAX(CASE WHEN f.raw_element = '6.19.a' THEN f.valore_num END) AS "q_6_19_a",
  MAX(CASE WHEN f.raw_element = '6.19.b' THEN f.valore_num END) AS "q_6_19_b",
  MAX(CASE WHEN f.raw_element = '6.19.c' THEN f.valore_num END) AS "q_6_19_c",
  MAX(CASE WHEN f.raw_element = '6.19.d' THEN f.valore_num END) AS "q_6_19_d",
  MAX(CASE WHEN f.raw_element = '6.2' THEN f.valore_num END) AS "q_6_2",
  MAX(CASE WHEN f.raw_element = '6.20.a' THEN f.valore_num END) AS "q_6_20_a",
  MAX(CASE WHEN f.raw_element = '6.20.b' THEN f.valore_num END) AS "q_6_20_b",
  MAX(CASE WHEN f.raw_element = '6.20.c' THEN f.valore_num END) AS "q_6_20_c",
  MAX(CASE WHEN f.raw_element = '6.20.d' THEN f.valore_num END) AS "q_6_20_d",
  MAX(CASE WHEN f.raw_element = '6.3.a' THEN f.valore_num END) AS "q_6_3_a",
  MAX(CASE WHEN f.raw_element = '6.3.b' THEN f.valore_num END) AS "q_6_3_b",
  MAX(CASE WHEN f.raw_element = '6.4.a' THEN f.valore_num END) AS "q_6_4_a",
  MAX(CASE WHEN f.raw_element = '6.4.b' THEN f.valore_num END) AS "q_6_4_b",
  MAX(CASE WHEN f.raw_element = '6.4.c' THEN f.valore_num END) AS "q_6_4_c",
  MAX(CASE WHEN f.raw_element = '6.4.d' THEN f.valore_num END) AS "q_6_4_d",
  MAX(CASE WHEN f.raw_element = '6.5' THEN f.valore_num END) AS "q_6_5",
  MAX(CASE WHEN f.raw_element = '6.5.a' THEN f.valore_num END) AS "q_6_5_a",
  MAX(CASE WHEN f.raw_element = '6.5.b' THEN f.valore_num END) AS "q_6_5_b",
  MAX(CASE WHEN f.raw_element = '6.5.c' THEN f.valore_num END) AS "q_6_5_c",
  MAX(CASE WHEN f.raw_element = '6.5.d' THEN f.valore_num END) AS "q_6_5_d",
  MAX(CASE WHEN f.raw_element = '6.6' THEN f.valore_num END) AS "q_6_6",
  MAX(CASE WHEN f.raw_element = '6.7' THEN f.valore_num END) AS "q_6_7",
  MAX(CASE WHEN f.raw_element = '6.8' THEN f.valore_num END) AS "q_6_8",
  MAX(CASE WHEN f.raw_element = '6.9' THEN f.valore_num END) AS "q_6_9"
FROM dwh.ft_questionari_globale f
LEFT JOIN dwh.lk_questionari_enti e ON e.codice_fiscale_ente = f.cf_ente
GROUP BY e.id, f.cf_ente, f.rilevazione, f.progetto;
