import type { FeatureFlag } from "./types";

/**
 * Catalogo delle funzionalità del sistema gestibili dall'Admin (on/off).
 * `label` coincide con l'etichetta usata dal tracker di utilizzo, così le
 * statistiche possono correlare eventi ↔ funzionalità.
 */
export const DEFAULT_FEATURE_FLAGS: FeatureFlag[] = [
  {
    key: "guided_navigation",
    label: "Navigazione Guidata",
    description: "Percorsi narrativi / Bussola (Pannello di Governo)",
    category: "Navigazione",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "technical_dashboard",
    label: "Vista Tecnica",
    description: "Cruscotto tecnico con indicatori e benchmark",
    category: "Navigazione",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "narrative_report",
    label: "Rapporto Narrativo",
    description: "Generazione del rapporto narrativo",
    category: "Navigazione",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "scheda_eta",
    label: "Analisi Età",
    description: "Scheda Conto Annuale — analisi anagrafica per età",
    category: "Schede Conto Annuale",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "scheda_anzianita",
    label: "Anzianità",
    description: "Scheda Conto Annuale — anzianità di servizio",
    category: "Schede Conto Annuale",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "scheda_assunti",
    label: "Assunti",
    description: "Scheda Conto Annuale — assunzioni per causale",
    category: "Schede Conto Annuale",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "scheda_cessazioni",
    label: "Cessazioni",
    description: "Scheda Conto Annuale — cessazioni per causale",
    category: "Schede Conto Annuale",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "scheda_turnover",
    label: "Turnover",
    description: "Scheda Conto Annuale — tasso di turnover",
    category: "Schede Conto Annuale",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "scheda_sostituzione",
    label: "Sostituzione",
    description: "Scheda Conto Annuale — tasso di sostituzione",
    category: "Schede Conto Annuale",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "scheda_formazione",
    label: "Formazione",
    description: "Scheda Conto Annuale — personale formato",
    category: "Schede Conto Annuale",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "scheda_progressioni",
    label: "Progressioni",
    description: "Scheda Conto Annuale — progressioni di carriera",
    category: "Schede Conto Annuale",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "scheda_analisi_personale",
    label: "Analisi del personale",
    description: "Scheda Conto Annuale — analisi del personale in servizio",
    category: "Schede Conto Annuale",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "scheda_lavoro_flessibile",
    label: "Lavoro flessibile",
    description: "Scheda Conto Annuale — contratti di lavoro flessibile",
    category: "Schede Conto Annuale",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "scheda_lavoro_agile",
    label: "Lavoro agile",
    description: "Scheda Conto Annuale — diffusione del lavoro agile",
    category: "Schede Conto Annuale",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "scheda_analisi_genere",
    label: "Analisi per genere",
    description: "Scheda Conto Annuale — analisi per genere",
    category: "Schede Conto Annuale",
    enabled: true,
    updatedAt: "",
  },
  // --- Schede SIPrO ---
  { key: "sipro_benchmark", label: "Benchmark DFP", description: "SIPrO — Benchmark multi-ente", category: "Schede SIPrO — Benchmark", enabled: true, updatedAt: "" },
  { key: "sipro_organigramma", label: "Organigramma UO", description: "SIPrO — Organizzazione", category: "Schede SIPrO — Organizzazione", enabled: true, updatedAt: "" },
  { key: "sipro_stato_org", label: "Stato Organizzazione", description: "SIPrO — Organizzazione", category: "Schede SIPrO — Organizzazione", enabled: true, updatedAt: "" },
  { key: "sipro_provvedimenti", label: "Provvedimenti Organizzativi", description: "SIPrO — Organizzazione", category: "Schede SIPrO — Organizzazione", enabled: true, updatedAt: "" },
  { key: "sipro_dotazione_uo", label: "Dotazione Risorse UO", description: "SIPrO — Organizzazione", category: "Schede SIPrO — Organizzazione", enabled: true, updatedAt: "" },
  { key: "sipro_criticita_uo", label: "Criticità UO", description: "SIPrO — Organizzazione", category: "Schede SIPrO — Organizzazione", enabled: true, updatedAt: "" },
  { key: "sipro_mappatura_processi", label: "Mappatura Processi", description: "SIPrO — Processi", category: "Schede SIPrO — Processi", enabled: true, updatedAt: "" },
  { key: "sipro_fasi_processi", label: "Fasi dei Processi", description: "SIPrO — Processi", category: "Schede SIPrO — Processi", enabled: true, updatedAt: "" },
  { key: "sipro_criticita_processi", label: "Criticità Processi", description: "SIPrO — Processi", category: "Schede SIPrO — Processi", enabled: true, updatedAt: "" },
  { key: "sipro_digitalizzazione", label: "Digitalizzazione Fasi", description: "SIPrO — Processi", category: "Schede SIPrO — Processi", enabled: true, updatedAt: "" },
  { key: "sipro_lavoro_agile", label: "Lavoro Agile Processi", description: "SIPrO — Processi", category: "Schede SIPrO — Processi", enabled: true, updatedAt: "" },
  { key: "sipro_outsourcing", label: "Outsourcing Fasi", description: "SIPrO — Processi", category: "Schede SIPrO — Processi", enabled: true, updatedAt: "" },
  { key: "sipro_semplificazione", label: "Semplificazione Processi", description: "SIPrO — Processi", category: "Schede SIPrO — Processi", enabled: true, updatedAt: "" },
  { key: "sipro_tempi_picchi", label: "Tempi e Picchi", description: "SIPrO — Processi", category: "Schede SIPrO — Processi", enabled: true, updatedAt: "" },
  { key: "sipro_fte", label: "FTE Programmati vs Assegnati", description: "SIPrO — Profili e Cataloghi", category: "Schede SIPrO — Profili e Cataloghi", enabled: true, updatedAt: "" },
  { key: "sipro_copertura", label: "Copertura Profili di Ruolo", description: "SIPrO — Profili e Cataloghi", category: "Schede SIPrO — Profili e Cataloghi", enabled: true, updatedAt: "" },
  { key: "sipro_catalogo_profili", label: "Catalogo Profili di Ruolo", description: "SIPrO — Profili e Cataloghi", category: "Schede SIPrO — Profili e Cataloghi", enabled: true, updatedAt: "" },
  { key: "sipro_fabbisogno", label: "Fabbisogno per Profilo", description: "SIPrO — Profili e Cataloghi", category: "Schede SIPrO — Profili e Cataloghi", enabled: true, updatedAt: "" },
  { key: "sipro_famiglie", label: "Famiglie Professionali", description: "SIPrO — Profili e Cataloghi", category: "Schede SIPrO — Profili e Cataloghi", enabled: true, updatedAt: "" },
  { key: "sipro_profili_minerva", label: "Profili Professionali Minerva", description: "SIPrO — Profili e Cataloghi", category: "Schede SIPrO — Profili e Cataloghi", enabled: true, updatedAt: "" },
  { key: "sipro_ambiti_ruolo", label: "Ambiti e Profili di Ruolo", description: "SIPrO — Profili e Cataloghi", category: "Schede SIPrO — Profili e Cataloghi", enabled: true, updatedAt: "" },
  { key: "sipro_aree_contrattuali", label: "Aree Contrattuali", description: "SIPrO — Profili e Cataloghi", category: "Schede SIPrO — Profili e Cataloghi", enabled: true, updatedAt: "" },
  { key: "sipro_evoluzione_profili", label: "Evoluzione Profili", description: "SIPrO — Profili e Cataloghi", category: "Schede SIPrO — Profili e Cataloghi", enabled: true, updatedAt: "" },
  {
    key: "export_dati",
    label: "Export Dati",
    description: "Esportazione tabelle e grafici (CSV/immagini)",
    category: "Sistema",
    enabled: true,
    updatedAt: "",
  },
  {
    key: "admin_panel",
    label: "Pannello Admin",
    description: "Accesso al pannello di amministrazione",
    category: "Sistema",
    enabled: true,
    updatedAt: "",
  },
];
