-- ============================================
-- MIGRAZIONE 3: Fact Tables principali
-- ============================================

-- ft_sipo_catalogo_processi
CREATE TABLE public.ft_sipo_catalogo_processi (
  processo_catalogo_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  data_fine timestamp NULL,
  denominazione varchar(100) NOT NULL,
  tipologia_id int2 NOT NULL,
  descrizione varchar(400) NOT NULL,
  descrizione_input varchar(400) NOT NULL,
  descrizione_output varchar(400) NOT NULL,
  coinvolgimento_amministrazioni int2 DEFAULT 0 NOT NULL,
  giorni_previsti int4 NULL,
  picchi_stagionali int2 DEFAULT 0 NOT NULL,
  presidio_continuativo int2 DEFAULT 0 NOT NULL,
  processo_semplificazione_id int2 NOT NULL,
  esecuzione_processo_id int2 DEFAULT 1 NOT NULL,
  ente_id int4 NULL,
  note_eliminazione varchar(1000) NULL,
  data_inserimento timestamp NOT NULL,
  user_inserimento_id int4 NOT NULL,
  data_modifica timestamp NULL,
  user_modifica_id int4 NULL,
  CONSTRAINT ft_sipo_catalogo_processi_pk PRIMARY KEY (processo_catalogo_id),
  CONSTRAINT ft_sipo_catalogo_processi_lk_enti FOREIGN KEY (ente_id) REFERENCES public.lk_enti(ente_id),
  CONSTRAINT ft_sipo_catalogo_processi_esecuzione_fk FOREIGN KEY (esecuzione_processo_id) REFERENCES public.lk_sipo_esecuzione_processo(esecuzione_processo_id),
  CONSTRAINT ft_sipo_catalogo_processi_semplificazione_fk FOREIGN KEY (processo_semplificazione_id) REFERENCES public.lk_sipo_semplificazione_processi(semplificazione_id),
  CONSTRAINT ft_sipo_catalogo_processi_tipologia_fk FOREIGN KEY (tipologia_id) REFERENCES public.lk_sipo_tipologia_funzione(tipologia_id),
  CONSTRAINT ft_sipo_catalogo_processi_login_fk FOREIGN KEY (user_inserimento_id) REFERENCES public.login(login_id),
  CONSTRAINT ft_sipo_catalogo_processi_login_fk2 FOREIGN KEY (user_modifica_id) REFERENCES public.login(login_id)
);
ALTER TABLE public.ft_sipo_catalogo_processi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on ft_sipo_catalogo_processi" ON public.ft_sipo_catalogo_processi FOR SELECT USING (true);

-- ft_sipo_catalogo_vincoli_processi
CREATE TABLE public.ft_sipo_catalogo_vincoli_processi (
  processo_catalogo_id int4 NOT NULL,
  vincoli_semplificazione_id int2 NOT NULL,
  CONSTRAINT ft_sipo_catalogo_vincoli_processi_pk PRIMARY KEY (processo_catalogo_id, vincoli_semplificazione_id),
  CONSTRAINT ft_sipo_catalogo_vincoli_catalogo_fk FOREIGN KEY (processo_catalogo_id) REFERENCES public.ft_sipo_catalogo_processi(processo_catalogo_id),
  CONSTRAINT ft_sipo_catalogo_vincoli_vincoli_fk FOREIGN KEY (vincoli_semplificazione_id) REFERENCES public.lk_sipo_vincoli_semplificazione_processi(vincolo_id)
);
ALTER TABLE public.ft_sipo_catalogo_vincoli_processi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on ft_sipo_catalogo_vincoli_processi" ON public.ft_sipo_catalogo_vincoli_processi FOR SELECT USING (true);

-- ft_sipo_organizzazione
CREATE TABLE public.ft_sipo_organizzazione (
  organizzazione_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ente_id int4 NOT NULL,
  stato_organizzazione_id int4 NOT NULL,
  denominazione varchar(100) NOT NULL,
  data_inserimento timestamp NOT NULL,
  user_inserimento_id int4 NOT NULL,
  data_modifica timestamp NULL,
  user_modifica_id int4 NULL,
  data_ultima_formalizzazione timestamp NULL,
  user_ultima_formalizzazione_id int4 NULL,
  data_eliminazione timestamp NULL,
  user_eliminazione_id int4 NULL,
  CONSTRAINT ft_sipo_organizzazione_pk PRIMARY KEY (organizzazione_id),
  CONSTRAINT ft_sipo_organizzazione_lk_enti_fk FOREIGN KEY (ente_id) REFERENCES public.lk_enti(ente_id),
  CONSTRAINT ft_sipo_organizzazione_stato_fk FOREIGN KEY (stato_organizzazione_id) REFERENCES public.lk_sipo_stato_organizzazione(stato_organizzazione_id),
  CONSTRAINT ft_sipo_organizzazione_login_fk FOREIGN KEY (user_inserimento_id) REFERENCES public.login(login_id),
  CONSTRAINT ft_sipo_organizzazione_login_fk1 FOREIGN KEY (user_modifica_id) REFERENCES public.login(login_id),
  CONSTRAINT ft_sipo_organizzazione_login_fk2 FOREIGN KEY (user_ultima_formalizzazione_id) REFERENCES public.login(login_id),
  CONSTRAINT ft_sipo_organizzazione_login_fk3 FOREIGN KEY (user_eliminazione_id) REFERENCES public.login(login_id)
);
ALTER TABLE public.ft_sipo_organizzazione ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on ft_sipo_organizzazione" ON public.ft_sipo_organizzazione FOR SELECT USING (true);

-- ft_sipo_provvedimenti_organizzazione
CREATE TABLE public.ft_sipo_provvedimenti_organizzazione (
  provvedimenti_organizzazione_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  organizzazione_id int4 NOT NULL,
  denominazione varchar(100) NOT NULL,
  data_adozione_provvedimento timestamp NOT NULL,
  data_formalizzazione timestamp NULL,
  user_formalizzazione_id int4 NULL,
  data_modifica timestamp NULL,
  user_modifica_id int4 NULL,
  data_eliminazione timestamp NULL,
  user_eliminazione_id int4 NULL,
  CONSTRAINT ft_sipo_provvedimenti_organizzazione_pk PRIMARY KEY (provvedimenti_organizzazione_id),
  CONSTRAINT ft_sipo_provvedimenti_organizzazione_org_fk FOREIGN KEY (organizzazione_id) REFERENCES public.ft_sipo_organizzazione(organizzazione_id),
  CONSTRAINT ft_sipo_provvedimenti_organizzazione_login_fk FOREIGN KEY (user_formalizzazione_id) REFERENCES public.login(login_id),
  CONSTRAINT ft_sipo_provvedimenti_organizzazione_login_fk2 FOREIGN KEY (user_modifica_id) REFERENCES public.login(login_id),
  CONSTRAINT ft_sipo_provvedimenti_organizzazione_login_fk3 FOREIGN KEY (user_eliminazione_id) REFERENCES public.login(login_id)
);
ALTER TABLE public.ft_sipo_provvedimenti_organizzazione ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on ft_sipo_provvedimenti_organizzazione" ON public.ft_sipo_provvedimenti_organizzazione FOR SELECT USING (true);

-- ft_sipo_uo
CREATE TABLE public.ft_sipo_uo (
  uo_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  parent_uo_id int4 NULL,
  ente_id int4 NOT NULL,
  data_fine_validita timestamp NULL,
  denominazione varchar(100) NOT NULL,
  nome_responsabile varchar(50) NULL,
  livello_gerarchico int2 NOT NULL,
  livello_resp_id int2 NOT NULL,
  risorse_dotazione float8 NOT NULL,
  risorse_servizio_tempo_ind float8 NOT NULL,
  descrizione_attivita varchar(1000) NULL,
  risorse_servizio_tempo_det float8 DEFAULT 0 NOT NULL,
  data_inserimento timestamp NOT NULL,
  user_inserimento_id int4 NOT NULL,
  data_modifica timestamp NULL,
  user_modifica_id int4 NULL,
  organizzazione_id int4 NOT NULL,
  CONSTRAINT ft_sipo_uo_pkey PRIMARY KEY (uo_id),
  CONSTRAINT ft_sipo_uo_enti_fk FOREIGN KEY (ente_id) REFERENCES public.lk_enti(ente_id),
  CONSTRAINT ft_sipo_uo_organizzazione_fk FOREIGN KEY (organizzazione_id) REFERENCES public.ft_sipo_organizzazione(organizzazione_id),
  CONSTRAINT ft_sipo_uo_livelli_resp_fk FOREIGN KEY (livello_resp_id) REFERENCES public.lk_sipo_livelli_resp_uo(livello_resp_id),
  CONSTRAINT ft_sipo_uo_login_fk FOREIGN KEY (user_inserimento_id) REFERENCES public.login(login_id),
  CONSTRAINT ft_sipo_uo_login_fk2 FOREIGN KEY (user_modifica_id) REFERENCES public.login(login_id)
);
ALTER TABLE public.ft_sipo_uo ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on ft_sipo_uo" ON public.ft_sipo_uo FOR SELECT USING (true);

-- ft_sipo_criticita_uo (dipende da ft_sipo_uo e lk_sipo_criticita_uo)
CREATE TABLE public.ft_sipo_criticita_uo (
  uo_id int4 NOT NULL,
  criticita_id char(3) NOT NULL,
  CONSTRAINT ft_sipo_criticita_uo_pk PRIMARY KEY (uo_id, criticita_id),
  CONSTRAINT ft_sipo_criticita_uo_uo_fk FOREIGN KEY (uo_id) REFERENCES public.ft_sipo_uo(uo_id),
  CONSTRAINT ft_sipo_criticita_uo_criticita_fk FOREIGN KEY (criticita_id) REFERENCES public.lk_sipo_criticita_uo(criticita_id)
);
ALTER TABLE public.ft_sipo_criticita_uo ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on ft_sipo_criticita_uo" ON public.ft_sipo_criticita_uo FOR SELECT USING (true);

-- ft_sipo_catalogo_fasi (dipende da ft_sipo_catalogo_processi, login)
CREATE TABLE public.ft_sipo_catalogo_fasi (
  processo_catalogo_id int4 NOT NULL,
  fase_catalogo_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ordinale int2 DEFAULT 1 NOT NULL,
  nome_fase varchar(100) NOT NULL,
  peso_fase int2 NOT NULL,
  descrizione varchar(500) NOT NULL,
  lavoro_agile_id int2 DEFAULT 0 NOT NULL,
  fase_digitale int2 DEFAULT 0 NOT NULL,
  fase_opzionale_id int2 DEFAULT 0 NOT NULL,
  data_inserimento timestamp NOT NULL,
  user_inserimento_id int4 NOT NULL,
  data_modifica timestamp NULL,
  user_modifica_id int4 NULL,
  CONSTRAINT ft_sipo_catalogo_fasi_pk PRIMARY KEY (fase_catalogo_id),
  CONSTRAINT ft_sipo_catalogo_fasi_catalogo_fk FOREIGN KEY (processo_catalogo_id) REFERENCES public.ft_sipo_catalogo_processi(processo_catalogo_id),
  CONSTRAINT ft_sipo_catalogo_fasi_login_fk FOREIGN KEY (user_inserimento_id) REFERENCES public.login(login_id),
  CONSTRAINT ft_sipo_catalogo_fasi_login_fk_1 FOREIGN KEY (user_modifica_id) REFERENCES public.login(login_id)
);
ALTER TABLE public.ft_sipo_catalogo_fasi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on ft_sipo_catalogo_fasi" ON public.ft_sipo_catalogo_fasi FOR SELECT USING (true);