-- ============================================
-- MIGRAZIONE 1: Tabelle Lookup senza FK + Tabelle di sistema indipendenti
-- ============================================

-- lk_enti
CREATE TABLE public.lk_enti (
  ente_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codice_ente varchar(20) NULL,
  denominazione varchar(70) NOT NULL,
  data_aggiornamento timestamp NOT NULL,
  citta varchar(50) NULL,
  provincia varchar(50) NULL,
  regione varchar(50) NULL,
  ripartizioni varchar(50) NULL,
  codice_ipa varchar(50) NULL,
  tipo varchar(50) NULL,
  comparto varchar(50) NULL,
  CONSTRAINT lk_enti_pkey PRIMARY KEY (ente_id)
);
ALTER TABLE public.lk_enti ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_enti" ON public.lk_enti FOR SELECT USING (true);

-- lk_minerva_comparto
CREATE TABLE public.lk_minerva_comparto (
  id int4 NOT NULL,
  descrizione varchar(50) NOT NULL,
  CONSTRAINT lk_minerva_comparto_pk PRIMARY KEY (id)
);
ALTER TABLE public.lk_minerva_comparto ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_minerva_comparto" ON public.lk_minerva_comparto FOR SELECT USING (true);

-- lk_picchi_frequenza_annuale_processi
CREATE TABLE public.lk_picchi_frequenza_annuale_processi (
  picchi_frequenza_id int2 NOT NULL,
  frequenza varchar(30) NOT NULL,
  CONSTRAINT lk_picchi_frequenza_annuale_processi_pkey PRIMARY KEY (picchi_frequenza_id)
);
ALTER TABLE public.lk_picchi_frequenza_annuale_processi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_picchi_frequenza_annuale_processi" ON public.lk_picchi_frequenza_annuale_processi FOR SELECT USING (true);

-- lk_picchi_intensita_processi
CREATE TABLE public.lk_picchi_intensita_processi (
  picchi_intensita_id int2 NOT NULL,
  intensita varchar(30) NOT NULL,
  CONSTRAINT lk_picchi_intensita_processi_pkey PRIMARY KEY (picchi_intensita_id)
);
ALTER TABLE public.lk_picchi_intensita_processi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_picchi_intensita_processi" ON public.lk_picchi_intensita_processi FOR SELECT USING (true);

-- lk_ruoli
CREATE TABLE public.lk_ruoli (
  ruolo_id int4 NOT NULL,
  nome varchar(50) NULL,
  abbreviazione varchar NULL,
  CONSTRAINT lk_ruoli_pkey PRIMARY KEY (ruolo_id)
);
ALTER TABLE public.lk_ruoli ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_ruoli" ON public.lk_ruoli FOR SELECT USING (true);

-- lk_sipo_copertura_profili_di_ruolo
CREATE TABLE public.lk_sipo_copertura_profili_di_ruolo (
  copertura_id int2 NOT NULL,
  range_min float8 NOT NULL,
  range_max float8 NOT NULL,
  descrizione varchar(20) NOT NULL,
  CONSTRAINT lk_sipo_copertura_profili_di_ruolo_pk PRIMARY KEY (copertura_id)
);
ALTER TABLE public.lk_sipo_copertura_profili_di_ruolo ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_copertura_profili_di_ruolo" ON public.lk_sipo_copertura_profili_di_ruolo FOR SELECT USING (true);

-- lk_sipo_criticita_processi
CREATE TABLE public.lk_sipo_criticita_processi (
  criticita_proc_id char(3) NOT NULL,
  categoria_proc_id int4 NOT NULL,
  categoria varchar(200) NOT NULL,
  descrizione varchar(400) NOT NULL,
  CONSTRAINT lk_sipo_criticita_processi_pkey PRIMARY KEY (criticita_proc_id)
);
ALTER TABLE public.lk_sipo_criticita_processi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_criticita_processi" ON public.lk_sipo_criticita_processi FOR SELECT USING (true);

-- lk_sipo_criticita_uo
CREATE TABLE public.lk_sipo_criticita_uo (
  criticita_id char(3) NOT NULL,
  categoria_id int4 NOT NULL,
  categoria varchar(60) NOT NULL,
  descrizione varchar(100) NOT NULL,
  CONSTRAINT lk_sipo_criticita_uo_pkey PRIMARY KEY (criticita_id)
);
ALTER TABLE public.lk_sipo_criticita_uo ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_criticita_uo" ON public.lk_sipo_criticita_uo FOR SELECT USING (true);

-- lk_sipo_esecuzione_processo
CREATE TABLE public.lk_sipo_esecuzione_processo (
  esecuzione_processo_id int2 NOT NULL,
  descrizione varchar(50) NOT NULL,
  CONSTRAINT lk_esecuzione_processo_id_pkey PRIMARY KEY (esecuzione_processo_id)
);
ALTER TABLE public.lk_sipo_esecuzione_processo ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_esecuzione_processo" ON public.lk_sipo_esecuzione_processo FOR SELECT USING (true);

-- lk_sipo_grado_rilevanza_processi
CREATE TABLE public.lk_sipo_grado_rilevanza_processi (
  grado_id int2 NOT NULL,
  descrizione varchar(100) NULL,
  dettaglio varchar(100) NULL,
  CONSTRAINT lk_sipo_grado_rilevanza_processi_pkey PRIMARY KEY (grado_id)
);
ALTER TABLE public.lk_sipo_grado_rilevanza_processi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_grado_rilevanza_processi" ON public.lk_sipo_grado_rilevanza_processi FOR SELECT USING (true);

-- lk_sipo_lavoro_agile_fasi
CREATE TABLE public.lk_sipo_lavoro_agile_fasi (
  lavoro_agile_id int4 NOT NULL,
  descrizione varchar(50) NOT NULL,
  CONSTRAINT lk_sipo_lavoro_agile_fasi_pk PRIMARY KEY (lavoro_agile_id)
);
ALTER TABLE public.lk_sipo_lavoro_agile_fasi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_lavoro_agile_fasi" ON public.lk_sipo_lavoro_agile_fasi FOR SELECT USING (true);

-- lk_sipo_livelli_resp_uo
CREATE TABLE public.lk_sipo_livelli_resp_uo (
  livello_resp_id int2 NOT NULL,
  descrizione varchar(30) NOT NULL,
  CONSTRAINT lk_sipo_livelli_resp_uo_pkey PRIMARY KEY (livello_resp_id)
);
ALTER TABLE public.lk_sipo_livelli_resp_uo ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_livelli_resp_uo" ON public.lk_sipo_livelli_resp_uo FOR SELECT USING (true);

-- lk_sipo_livello_digitalizzazione_fasi
CREATE TABLE public.lk_sipo_livello_digitalizzazione_fasi (
  livello_digitalizzazione_id int2 NOT NULL,
  descrizione varchar(30) NULL,
  valore int4 DEFAULT 0 NULL,
  CONSTRAINT lk_sipo_livello_digitalizzazione_fasi_pkey PRIMARY KEY (livello_digitalizzazione_id)
);
ALTER TABLE public.lk_sipo_livello_digitalizzazione_fasi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_livello_digitalizzazione_fasi" ON public.lk_sipo_livello_digitalizzazione_fasi FOR SELECT USING (true);

-- lk_sipo_obiettivi_strategici_processi
CREATE TABLE public.lk_sipo_obiettivi_strategici_processi (
  obiettivo_id int2 NOT NULL,
  descrizione varchar(30) NOT NULL,
  CONSTRAINT lk_sipo_obiettivi_strategici_processi_pkey PRIMARY KEY (obiettivo_id)
);
ALTER TABLE public.lk_sipo_obiettivi_strategici_processi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_obiettivi_strategici_processi" ON public.lk_sipo_obiettivi_strategici_processi FOR SELECT USING (true);

-- lk_sipo_opzionale_fasi
CREATE TABLE public.lk_sipo_opzionale_fasi (
  fase_opzionale_id int4 NOT NULL,
  descrizione varchar(100) NOT NULL,
  CONSTRAINT lk_sipo_opzionale_fasi_pk PRIMARY KEY (fase_opzionale_id)
);
ALTER TABLE public.lk_sipo_opzionale_fasi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_opzionale_fasi" ON public.lk_sipo_opzionale_fasi FOR SELECT USING (true);

-- lk_sipo_outsourcing_fasi
CREATE TABLE public.lk_sipo_outsourcing_fasi (
  outsourcing_id int4 NOT NULL,
  descrizione varchar(100) NOT NULL,
  valore int4 DEFAULT 0 NULL,
  CONSTRAINT lk_sipo_outsourcing_fasi_pk PRIMARY KEY (outsourcing_id)
);
ALTER TABLE public.lk_sipo_outsourcing_fasi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_outsourcing_fasi" ON public.lk_sipo_outsourcing_fasi FOR SELECT USING (true);

-- lk_sipo_semplificazione_processi
CREATE TABLE public.lk_sipo_semplificazione_processi (
  semplificazione_id int2 NOT NULL,
  descrizione varchar(100) NULL,
  CONSTRAINT lk_sipo_semplificazione_processi_pkey PRIMARY KEY (semplificazione_id)
);
ALTER TABLE public.lk_sipo_semplificazione_processi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_semplificazione_processi" ON public.lk_sipo_semplificazione_processi FOR SELECT USING (true);

-- lk_sipo_stato_organizzazione
CREATE TABLE public.lk_sipo_stato_organizzazione (
  stato_organizzazione_id int4 NOT NULL,
  descrizione varchar(20) NOT NULL,
  CONSTRAINT lk_sipo_stato_organizzazione_pk PRIMARY KEY (stato_organizzazione_id)
);
ALTER TABLE public.lk_sipo_stato_organizzazione ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_stato_organizzazione" ON public.lk_sipo_stato_organizzazione FOR SELECT USING (true);

-- lk_sipo_stato_processi
CREATE TABLE public.lk_sipo_stato_processi (
  stato_processo_id int4 NOT NULL,
  descrizione varchar(20) NOT NULL,
  CONSTRAINT lk_sipo_stato_processi_pk PRIMARY KEY (stato_processo_id)
);
ALTER TABLE public.lk_sipo_stato_processi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_stato_processi" ON public.lk_sipo_stato_processi FOR SELECT USING (true);

-- lk_sipo_tipologia_funzione
CREATE TABLE public.lk_sipo_tipologia_funzione (
  tipologia_id int2 NOT NULL,
  funzione varchar(30) NOT NULL,
  tipologia varchar(100) NOT NULL,
  CONSTRAINT lk_sipo_tipologia_funzione_pkey PRIMARY KEY (tipologia_id)
);
ALTER TABLE public.lk_sipo_tipologia_funzione ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_tipologia_funzione" ON public.lk_sipo_tipologia_funzione FOR SELECT USING (true);

-- lk_sipo_tipologia_ruolo_processi
CREATE TABLE public.lk_sipo_tipologia_ruolo_processi (
  tipologia_ruolo_id int4 NOT NULL,
  tipologia varchar(30) NOT NULL,
  CONSTRAINT lk_sipo_tipologia_ruolo_processi_pkey PRIMARY KEY (tipologia_ruolo_id)
);
ALTER TABLE public.lk_sipo_tipologia_ruolo_processi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_tipologia_ruolo_processi" ON public.lk_sipo_tipologia_ruolo_processi FOR SELECT USING (true);

-- lk_sipo_uo
CREATE TABLE public.lk_sipo_uo (
  uo_id int2 NOT NULL,
  descrizione varchar(50) NULL,
  CONSTRAINT lk_sipo_uo_pkey PRIMARY KEY (uo_id)
);
ALTER TABLE public.lk_sipo_uo ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_uo" ON public.lk_sipo_uo FOR SELECT USING (true);

-- lk_sipo_vincoli_semplificazione_processi
CREATE TABLE public.lk_sipo_vincoli_semplificazione_processi (
  vincolo_id int2 NOT NULL,
  descrizione varchar(50) NULL,
  CONSTRAINT lk_sipo_vincoli_semplificazione_processi_pkey PRIMARY KEY (vincolo_id)
);
ALTER TABLE public.lk_sipo_vincoli_semplificazione_processi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on lk_sipo_vincoli_semplificazione_processi" ON public.lk_sipo_vincoli_semplificazione_processi FOR SELECT USING (true);

-- login_enti
CREATE TABLE public.login_enti (
  login_id int4 NOT NULL,
  ente_id int4 NOT NULL,
  CONSTRAINT login_enti_pk PRIMARY KEY (login_id, ente_id)
);
ALTER TABLE public.login_enti ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on login_enti" ON public.login_enti FOR SELECT USING (true);

-- sipo_audit_log
CREATE TABLE public.sipo_audit_log (
  audit_log_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "timestamp" timestamp NULL,
  service_name varchar(100) NULL,
  entity_name varchar(50) NULL,
  entity_id varchar(50) NULL,
  operation varchar(50) NULL,
  old_value text NULL,
  new_value text NULL,
  user_id int4 NULL,
  correlation_id varchar(50) NULL,
  ente_id int4 NULL,
  error int4 NULL,
  CONSTRAINT audit_log_id PRIMARY KEY (audit_log_id)
);
ALTER TABLE public.sipo_audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on sipo_audit_log" ON public.sipo_audit_log FOR SELECT USING (true);