-- ============================================
-- MIGRAZIONE 4: Fact tables rimanenti (dipendono da ft_sipo_uo, ft_sipo_catalogo_processi, ft_sipo_processi)
-- ============================================

-- ft_sipo_processi
CREATE TABLE public.ft_sipo_processi (
  processo_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ente_id int4 NOT NULL,
  data_fine timestamp NULL,
  denominazione varchar(100) NOT NULL,
  tipologia_id int2 NOT NULL,
  descrizione varchar(400) NOT NULL,
  uo_responsabile_id int4 NULL,
  obiettivo_strategico_id int2 NULL,
  grado_rilevanza_id int2 NULL,
  descrizione_input varchar(400) NOT NULL,
  descrizione_output varchar(400) NOT NULL,
  coinvolgimento_amministrazioni int2 DEFAULT 0 NOT NULL,
  giorni_previsti int4 NULL,
  tempo_medio_effettivo int4 NULL,
  picchi_stagionali int2 DEFAULT 0 NOT NULL,
  picchi_frequenza_id int2 NULL,
  picchi_intensita_id int2 NULL,
  picchi_descrizione varchar(400) NULL,
  presidio_continuativo int2 DEFAULT 0 NOT NULL,
  processo_semplificazione_id int2 NOT NULL,
  da_catalogo int2 DEFAULT 0 NOT NULL,
  note_compilatore varchar(1000) NULL,
  esecuzione_processo_id int2 DEFAULT 1 NOT NULL,
  catalogo_processo_id int4 NULL,
  stato_processo_id int4 DEFAULT 1 NOT NULL,
  data_pubblicazione timestamp NULL,
  utente_pubblicazione_id int4 NULL,
  note_revisione varchar(1000) NULL,
  data_revisione timestamp NULL,
  utente_revisione_id int4 NULL,
  data_validazione timestamp NULL,
  utente_validazione_id int4 NULL,
  data_inserimento timestamp NOT NULL,
  user_inserimento_id int4 NOT NULL,
  data_modifica timestamp NULL,
  user_modifica_id int4 NULL,
  CONSTRAINT ft_sipo_processi_pkey PRIMARY KEY (processo_id),
  CONSTRAINT ft_sipo_processi_catalogo_fk FOREIGN KEY (catalogo_processo_id) REFERENCES public.ft_sipo_catalogo_processi(processo_catalogo_id),
  CONSTRAINT ft_sipo_processi_uo_fk FOREIGN KEY (uo_responsabile_id) REFERENCES public.ft_sipo_uo(uo_id),
  CONSTRAINT ft_sipo_processi_lk_enti_fk FOREIGN KEY (ente_id) REFERENCES public.lk_enti(ente_id),
  CONSTRAINT ft_sipo_processi_picchi_frequenza_fk FOREIGN KEY (picchi_frequenza_id) REFERENCES public.lk_picchi_frequenza_annuale_processi(picchi_frequenza_id),
  CONSTRAINT ft_sipo_processi_picchi_intensita_fk FOREIGN KEY (picchi_intensita_id) REFERENCES public.lk_picchi_intensita_processi(picchi_intensita_id),
  CONSTRAINT ft_sipo_processi_esecuzione_fk FOREIGN KEY (esecuzione_processo_id) REFERENCES public.lk_sipo_esecuzione_processo(esecuzione_processo_id),
  CONSTRAINT ft_sipo_processi_rilevanza_fk FOREIGN KEY (grado_rilevanza_id) REFERENCES public.lk_sipo_grado_rilevanza_processi(grado_id),
  CONSTRAINT ft_sipo_processi_obiettivi_fk FOREIGN KEY (obiettivo_strategico_id) REFERENCES public.lk_sipo_obiettivi_strategici_processi(obiettivo_id),
  CONSTRAINT ft_sipo_processi_semplificazione_fk FOREIGN KEY (processo_semplificazione_id) REFERENCES public.lk_sipo_semplificazione_processi(semplificazione_id),
  CONSTRAINT ft_sipo_processi_stato_fk FOREIGN KEY (stato_processo_id) REFERENCES public.lk_sipo_stato_processi(stato_processo_id),
  CONSTRAINT ft_sipo_processi_tipologia_fk FOREIGN KEY (tipologia_id) REFERENCES public.lk_sipo_tipologia_funzione(tipologia_id),
  CONSTRAINT ft_sipo_processi_login_fk FOREIGN KEY (user_inserimento_id) REFERENCES public.login(login_id),
  CONSTRAINT ft_sipo_processi_login_fk2 FOREIGN KEY (user_modifica_id) REFERENCES public.login(login_id),
  CONSTRAINT ft_sipo_processi_login_pubblicazione_fk FOREIGN KEY (utente_pubblicazione_id) REFERENCES public.login(login_id),
  CONSTRAINT ft_sipo_processi_login_revisione_fk FOREIGN KEY (utente_revisione_id) REFERENCES public.login(login_id),
  CONSTRAINT ft_sipo_processi_login_validazione_fk FOREIGN KEY (utente_validazione_id) REFERENCES public.login(login_id)
);
ALTER TABLE public.ft_sipo_processi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on ft_sipo_processi" ON public.ft_sipo_processi FOR SELECT USING (true);

-- ft_sipo_vincoli_processi
CREATE TABLE public.ft_sipo_vincoli_processi (
  processo_id int4 NOT NULL,
  vincoli_semplificazione_id int2 NOT NULL,
  CONSTRAINT ft_sipo_vincoli_processi_pk PRIMARY KEY (processo_id, vincoli_semplificazione_id),
  CONSTRAINT ft_sipo_vincoli_processi_processi_fk FOREIGN KEY (processo_id) REFERENCES public.ft_sipo_processi(processo_id),
  CONSTRAINT ft_sipo_vincoli_processi_vincoli_fk FOREIGN KEY (vincoli_semplificazione_id) REFERENCES public.lk_sipo_vincoli_semplificazione_processi(vincolo_id)
);
ALTER TABLE public.ft_sipo_vincoli_processi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on ft_sipo_vincoli_processi" ON public.ft_sipo_vincoli_processi FOR SELECT USING (true);

-- ft_sipo_criticita_processi
CREATE TABLE public.ft_sipo_criticita_processi (
  processo_id int4 NOT NULL,
  criticita_processo_id char(3) NOT NULL,
  CONSTRAINT ft_sipo_criticita_processi_pk PRIMARY KEY (processo_id, criticita_processo_id),
  CONSTRAINT ft_sipo_criticita_processi_processi_fk FOREIGN KEY (processo_id) REFERENCES public.ft_sipo_processi(processo_id),
  CONSTRAINT ft_sipo_criticita_processi_criticita_fk FOREIGN KEY (criticita_processo_id) REFERENCES public.lk_sipo_criticita_processi(criticita_proc_id)
);
ALTER TABLE public.ft_sipo_criticita_processi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on ft_sipo_criticita_processi" ON public.ft_sipo_criticita_processi FOR SELECT USING (true);

-- ft_sipo_fasi
CREATE TABLE public.ft_sipo_fasi (
  processo_id int4 NOT NULL,
  fase_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  parent_id int2 NULL,
  ordinale int2 DEFAULT 1 NOT NULL,
  nome_fase varchar(100) NOT NULL,
  peso_fase int2 NOT NULL,
  descrizione varchar(500) NOT NULL,
  uo_responsabile_id int4 NULL,
  lavoro_agile int2 DEFAULT 0 NOT NULL,
  in_outsourcing int2 DEFAULT 0 NOT NULL,
  fase_digitale int2 DEFAULT 0 NOT NULL,
  livello_digitalizzazione_id int2 NULL,
  fase_opzionale int2 DEFAULT 0 NOT NULL,
  data_inserimento timestamp NOT NULL,
  lavoro_agile_id int2 DEFAULT 0 NOT NULL,
  outsourcing_id int2 DEFAULT 0 NOT NULL,
  fase_opzionale_id int2 DEFAULT 0 NOT NULL,
  user_inserimento_id int4 NOT NULL,
  data_modifica timestamp NULL,
  user_modifica_id int4 NULL,
  CONSTRAINT ft_sipo_fasi_pkey PRIMARY KEY (fase_id),
  CONSTRAINT ft_sipo_fasi_processi_fk FOREIGN KEY (processo_id) REFERENCES public.ft_sipo_processi(processo_id),
  CONSTRAINT ft_sipo_fasi_lavoro_agile_fk FOREIGN KEY (lavoro_agile_id) REFERENCES public.lk_sipo_lavoro_agile_fasi(lavoro_agile_id),
  CONSTRAINT ft_sipo_fasi_digitalizzazione_fk FOREIGN KEY (livello_digitalizzazione_id) REFERENCES public.lk_sipo_livello_digitalizzazione_fasi(livello_digitalizzazione_id),
  CONSTRAINT ft_sipo_fasi_opzionale_fk FOREIGN KEY (fase_opzionale_id) REFERENCES public.lk_sipo_opzionale_fasi(fase_opzionale_id),
  CONSTRAINT ft_sipo_fasi_outsourcing_fk FOREIGN KEY (outsourcing_id) REFERENCES public.lk_sipo_outsourcing_fasi(outsourcing_id)
);
ALTER TABLE public.ft_sipo_fasi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on ft_sipo_fasi" ON public.ft_sipo_fasi FOR SELECT USING (true);

-- ft_sipo_fasi_uo_partecipanti
CREATE TABLE public.ft_sipo_fasi_uo_partecipanti (
  fase_id int2 NOT NULL,
  uo_partecipante_id int2 NOT NULL,
  CONSTRAINT ft_sipo_fasi_uo_partecipanti_pk PRIMARY KEY (fase_id, uo_partecipante_id),
  CONSTRAINT ft_sipo_fasi_uo_partecipanti_fasi_fk FOREIGN KEY (fase_id) REFERENCES public.ft_sipo_fasi(fase_id),
  CONSTRAINT ft_sipo_fasi_uo_partecipanti_uo_fk FOREIGN KEY (uo_partecipante_id) REFERENCES public.ft_sipo_uo(uo_id)
);
ALTER TABLE public.ft_sipo_fasi_uo_partecipanti ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on ft_sipo_fasi_uo_partecipanti" ON public.ft_sipo_fasi_uo_partecipanti FOR SELECT USING (true);

-- ft_sipo_profili_di_ruolo_fasi
CREATE TABLE public.ft_sipo_profili_di_ruolo_fasi (
  id_profilo_di_ruolo int4 NULL,
  fte_programmati float4 NOT NULL,
  fte_assegnati float4 NOT NULL,
  percentuale_impegno int2 NOT NULL,
  fase_id int4 NOT NULL,
  profilo_fase_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  sipo_profilo_di_ruolo_id int4 NULL,
  riva_profilo_di_ruolo_id int4 NULL,
  CONSTRAINT ft_sipo_profili_di_ruolo_fasi_pkey PRIMARY KEY (profilo_fase_id),
  CONSTRAINT ft_sipo_profili_di_ruolo_fasi_fasi_fk FOREIGN KEY (fase_id) REFERENCES public.ft_sipo_fasi(fase_id)
);
ALTER TABLE public.ft_sipo_profili_di_ruolo_fasi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on ft_sipo_profili_di_ruolo_fasi" ON public.ft_sipo_profili_di_ruolo_fasi FOR SELECT USING (true);